#
# Makefile for Phoenix-RTOS
#
# Copyright 2025 Phoenix Systems
#

ifeq ($(PCI_EXPRESS_XILINX_NWL),y)
  NAME := pcie-xilinx-nwl
  LOCAL_SRCS := pcie-xilinx-nwl.c
  LOCAL_HEADERS := pcie-xilinx-nwl.h
  include $(static-lib.mk)
endif
