#
# Makefile for Phoenix-RTOS cmsdk-apbuart driver
#
# Copyright 2024 Phoenix Systems
#
# %LICENSE%
#

NAME := cmsdk-apbuart
LOCAL_SRCS := cmsdk-apbuart.c
DEP_LIBS := libtty libklog
include $(binary.mk)
