#
# Makefile for Phoenix-RTOS imx6ull-otp
#
# Copyright 2018, 2019 Phoenix Systems
#

$(PREFIX_PROG)imx6ull-otp: $(PREFIX_O)utils/imx6ull-otp/imx6ull-otp.o
	$(LINK)

all: $(PREFIX_PROG_STRIPPED)imx6ull-otp
