#
# Makefile for Phoenix-RTOS spacewire
#
# Copyright 2025 Phoenix Systems
#
# SPDX-License-Identifier: BSD-3-Clause
#

NAME := libgrspw
LOCAL_HEADERS := libgrspw.h
LOCAL_SRCS := libgrspw.c

include $(static-lib.mk)
