#
# Makefile for Phoenix-RTOS pc-ata driver
#
# Copyright 2017, 2018 Phoenix Systems
# Copyright 2001, 2005-2006 Pawel Pisarczyk
#

PROGS := pc-ata

# FIXME
#CFLAGS += -I../../pci/pc-pci

# include after all dependencies are set
include $(TOPDIR)/Makefile.rules
