#
# Makefile for Phoenix-RTOS pc-uart driver
#
# Copyright 2017, 2018 Phoenix Systems
# Copyright 2001, 2005-2006 Pawel Pisarczyk
#

$(PREFIX_PROG)pc-uart: $(PREFIX_O)tty/pc-uart/pc-uart.o
	$(LINK)

all: $(PREFIX_PROG_STRIPPED)pc-uart
