#
# Makefile for Phoenix-RTOS pc-uart driver
#
# Copyright 2017, 2018 Phoenix Systems
# Copyright 2001, 2005-2006 Pawel Pisarczyk
#

PROGS := pc-uart

# include after all dependencies are set
include $(TOPDIR)/Makefile.rules
