#
# Makefile for Phoenix-RTOS
#
# Copyright 2025 Phoenix Systems
#
NAME := pcie-clock
LOCAL_SRCS := pcie-clock.c
DEP_LIBS := i2c-common libi2c-msg
include $(binary.mk)

NAME := pcie-phy
LOCAL_SRCS := pcie-phy.c
include $(binary.mk)
