/*
 * Phoenix-RTOS
 *
 * IMX6ULL mux definitions
 *
 * NOTE: This file was generated from datasheet using internal tools. See
 * (non-public) devtools repo for details. To be determined what is the
 * correct way to upstream those tools and source data into public repo.
 *
 * Copyright 2026 Phoenix Systems
 * Author: Jan Wiśniewski
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */


/* clang-format off */
#ifndef IOMUX_MUX_ENUMS_H
#define IOMUX_MUX_ENUMS_H

#ifdef __cplusplus
extern "C" {
#endif

enum {
    ALT0 = 0,
    ALT1 = 1,
    ALT2 = 2,
    ALT3 = 3,
    ALT4 = 4,
    ALT5 = 5,
    ALT6 = 6,
    ALT7 = 7,
    ALT8 = 8,
    ALT9 = 9
};

enum MUX_PAD_BOOT_MODE0 {
    MUX_PAD_BOOT_MODE0__GPIO5_IO10 = ALT5
};

enum MUX_PAD_SNVS_TAMPER0 {
    MUX_PAD_SNVS_TAMPER0__GPIO5_IO00 = ALT5
};

enum MUX_PAD_SNVS_TAMPER1 {
    MUX_PAD_SNVS_TAMPER1__GPIO5_IO01 = ALT5
};

enum MUX_PAD_SNVS_TAMPER2 {
    MUX_PAD_SNVS_TAMPER2__GPIO5_IO02 = ALT5
};

enum MUX_PAD_SNVS_TAMPER3 {
    MUX_PAD_SNVS_TAMPER3__GPIO5_IO03 = ALT5
};

enum MUX_PAD_SNVS_TAMPER4 {
    MUX_PAD_SNVS_TAMPER4__GPIO5_IO04 = ALT5
};

enum MUX_PAD_SNVS_TAMPER5 {
    MUX_PAD_SNVS_TAMPER5__GPIO5_IO05 = ALT5
};

enum MUX_PAD_SNVS_TAMPER6 {
    MUX_PAD_SNVS_TAMPER6__GPIO5_IO06 = ALT5
};

enum MUX_PAD_SNVS_TAMPER7 {
    MUX_PAD_SNVS_TAMPER7__GPIO5_IO07 = ALT5
};

enum MUX_PAD_SNVS_TAMPER8 {
    MUX_PAD_SNVS_TAMPER8__GPIO05_IO08 = ALT5
};

enum MUX_PAD_SNVS_TAMPER9 {
    MUX_PAD_SNVS_TAMPER9__GPIO5_IO09 = ALT5
};

enum MUX_PAD_CSI_DATA00 {
    MUX_PAD_CSI_DATA00__CSI_DATA02 = ALT0,
    MUX_PAD_CSI_DATA00__USDHC2_DATA0 = ALT1,
    MUX_PAD_CSI_DATA00__RESERVED_ALT2 = ALT2,
    MUX_PAD_CSI_DATA00__ECSPI2_SCLK = ALT3,
    MUX_PAD_CSI_DATA00__EIM_AD00 = ALT4,
    MUX_PAD_CSI_DATA00__GPIO4_IO21 = ALT5,
    MUX_PAD_CSI_DATA00__SRC_INT_BOOT = ALT6,
    MUX_PAD_CSI_DATA00__UART5_TX = ALT8,
    MUX_PAD_CSI_DATA00__ESAI_TX_HF_CLK = ALT9
};

enum MUX_PAD_CSI_DATA01 {
    MUX_PAD_CSI_DATA01__CSI_DATA03 = ALT0,
    MUX_PAD_CSI_DATA01__USDHC2_DATA1 = ALT1,
    MUX_PAD_CSI_DATA01__RESERVED_ALT2 = ALT2,
    MUX_PAD_CSI_DATA01__ECSPI2_SS0 = ALT3,
    MUX_PAD_CSI_DATA01__EIM_AD01 = ALT4,
    MUX_PAD_CSI_DATA01__GPIO4_IO22 = ALT5,
    MUX_PAD_CSI_DATA01__SAI1_MCLK = ALT6,
    MUX_PAD_CSI_DATA01__UART5_RX = ALT8,
    MUX_PAD_CSI_DATA01__ESAI_RX_HF_CLK = ALT9
};

enum MUX_PAD_CSI_DATA02 {
    MUX_PAD_CSI_DATA02__CSI_DATA04 = ALT0,
    MUX_PAD_CSI_DATA02__USDHC2_DATA2 = ALT1,
    MUX_PAD_CSI_DATA02__RESERVED_ALT2 = ALT2,
    MUX_PAD_CSI_DATA02__ECSPI2_MOSI = ALT3,
    MUX_PAD_CSI_DATA02__EIM_AD02 = ALT4,
    MUX_PAD_CSI_DATA02__GPIO4_IO23 = ALT5,
    MUX_PAD_CSI_DATA02__SAI1_RX_SYNC = ALT6,
    MUX_PAD_CSI_DATA02__UART5_RTS_B = ALT8,
    MUX_PAD_CSI_DATA02__ESAI_RX_FS = ALT9
};

enum MUX_PAD_CSI_DATA03 {
    MUX_PAD_CSI_DATA03__CSI_DATA05 = ALT0,
    MUX_PAD_CSI_DATA03__USDHC2_DATA3 = ALT1,
    MUX_PAD_CSI_DATA03__RESERVED_ALT2 = ALT2,
    MUX_PAD_CSI_DATA03__ECSPI2_MISO = ALT3,
    MUX_PAD_CSI_DATA03__EIM_AD03 = ALT4,
    MUX_PAD_CSI_DATA03__GPIO4_IO24 = ALT5,
    MUX_PAD_CSI_DATA03__SAI1_RX_BCLK = ALT6,
    MUX_PAD_CSI_DATA03__UART5_CTS_B = ALT8,
    MUX_PAD_CSI_DATA03__ESAI_RX_CLK = ALT9
};

enum MUX_PAD_CSI_DATA04 {
    MUX_PAD_CSI_DATA04__CSI_DATA06 = ALT0,
    MUX_PAD_CSI_DATA04__USDHC2_DATA4 = ALT1,
    MUX_PAD_CSI_DATA04__RESERVED_ALT2 = ALT2,
    MUX_PAD_CSI_DATA04__ECSPI1_SCLK = ALT3,
    MUX_PAD_CSI_DATA04__EIM_AD04 = ALT4,
    MUX_PAD_CSI_DATA04__GPIO4_IO25 = ALT5,
    MUX_PAD_CSI_DATA04__SAI1_TX_SYNC = ALT6,
    MUX_PAD_CSI_DATA04__USDHC1_WP = ALT8,
    MUX_PAD_CSI_DATA04__ESAI_TX_FS = ALT9
};

enum MUX_PAD_CSI_DATA05 {
    MUX_PAD_CSI_DATA05__CSI_DATA07 = ALT0,
    MUX_PAD_CSI_DATA05__USDHC2_DATA5 = ALT1,
    MUX_PAD_CSI_DATA05__RESERVED_ALT2 = ALT2,
    MUX_PAD_CSI_DATA05__ECSPI1_SS0 = ALT3,
    MUX_PAD_CSI_DATA05__EIM_AD05 = ALT4,
    MUX_PAD_CSI_DATA05__GPIO4_IO26 = ALT5,
    MUX_PAD_CSI_DATA05__SAI1_TX_BCLK = ALT6,
    MUX_PAD_CSI_DATA05__USDHC1_CD_B = ALT8,
    MUX_PAD_CSI_DATA05__ESAI_TX_CLK = ALT9
};

enum MUX_PAD_CSI_DATA06 {
    MUX_PAD_CSI_DATA06__CSI_DATA08 = ALT0,
    MUX_PAD_CSI_DATA06__USDHC2_DATA6 = ALT1,
    MUX_PAD_CSI_DATA06__RESERVED_ALT2 = ALT2,
    MUX_PAD_CSI_DATA06__ECSPI1_MOSI = ALT3,
    MUX_PAD_CSI_DATA06__EIM_AD06 = ALT4,
    MUX_PAD_CSI_DATA06__GPIO4_IO27 = ALT5,
    MUX_PAD_CSI_DATA06__SAI1_RX_DATA = ALT6,
    MUX_PAD_CSI_DATA06__USDHC1_RESET_B = ALT8,
    MUX_PAD_CSI_DATA06__ESAI_TX5_RX0 = ALT9
};

enum MUX_PAD_CSI_DATA07 {
    MUX_PAD_CSI_DATA07__CSI_DATA09 = ALT0,
    MUX_PAD_CSI_DATA07__USDHC2_DATA7 = ALT1,
    MUX_PAD_CSI_DATA07__RESERVED_ALT2 = ALT2,
    MUX_PAD_CSI_DATA07__ECSPI1_MISO = ALT3,
    MUX_PAD_CSI_DATA07__EIM_AD07 = ALT4,
    MUX_PAD_CSI_DATA07__GPIO4_IO28 = ALT5,
    MUX_PAD_CSI_DATA07__SAI1_TX_DATA = ALT6,
    MUX_PAD_CSI_DATA07__USDHC1_VSELECT = ALT8,
    MUX_PAD_CSI_DATA07__ESAI_TX0 = ALT9
};

enum MUX_PAD_CSI_HSYNC {
    MUX_PAD_CSI_HSYNC__CSI_HSYNC = ALT0,
    MUX_PAD_CSI_HSYNC__USDHC2_CMD = ALT1,
    MUX_PAD_CSI_HSYNC__RESERVED_ALT2 = ALT2,
    MUX_PAD_CSI_HSYNC__I2C2_SCL = ALT3,
    MUX_PAD_CSI_HSYNC__EIM_LBA_B = ALT4,
    MUX_PAD_CSI_HSYNC__GPIO4_IO20 = ALT5,
    MUX_PAD_CSI_HSYNC__PWM8_OUT = ALT6,
    MUX_PAD_CSI_HSYNC__UART6_CTS_B = ALT8,
    MUX_PAD_CSI_HSYNC__ESAI_TX1 = ALT9
};

enum MUX_PAD_CSI_MCLK {
    MUX_PAD_CSI_MCLK__CSI_MCLK = ALT0,
    MUX_PAD_CSI_MCLK__USDHC2_CD_B = ALT1,
    MUX_PAD_CSI_MCLK__RAWNAND_CE2_B = ALT2,
    MUX_PAD_CSI_MCLK__I2C1_SDA = ALT3,
    MUX_PAD_CSI_MCLK__EIM_CS0_B = ALT4,
    MUX_PAD_CSI_MCLK__GPIO4_IO17 = ALT5,
    MUX_PAD_CSI_MCLK__SNVS_HP_VIO_5_CTL = ALT6,
    MUX_PAD_CSI_MCLK__UART6_TX = ALT8,
    MUX_PAD_CSI_MCLK__ESAI_TX3_RX2 = ALT9
};

enum MUX_PAD_CSI_PIXCLK {
    MUX_PAD_CSI_PIXCLK__CSI_PIXCLK = ALT0,
    MUX_PAD_CSI_PIXCLK__USDHC2_WP = ALT1,
    MUX_PAD_CSI_PIXCLK__RAWNAND_CE3_B = ALT2,
    MUX_PAD_CSI_PIXCLK__I2C1_SCL = ALT3,
    MUX_PAD_CSI_PIXCLK__EIM_OE = ALT4,
    MUX_PAD_CSI_PIXCLK__GPIO4_IO18 = ALT5,
    MUX_PAD_CSI_PIXCLK__SNVS_HP_VIO_5 = ALT6,
    MUX_PAD_CSI_PIXCLK__UART6_RX = ALT8,
    MUX_PAD_CSI_PIXCLK__ESAI_TX2_RX3 = ALT9
};

enum MUX_PAD_CSI_VSYNC {
    MUX_PAD_CSI_VSYNC__CSI_VSYNC = ALT0,
    MUX_PAD_CSI_VSYNC__USDHC2_CLK = ALT1,
    MUX_PAD_CSI_VSYNC__RESERVED_ALT2 = ALT2,
    MUX_PAD_CSI_VSYNC__I2C2_SDA = ALT3,
    MUX_PAD_CSI_VSYNC__EIM_RW = ALT4,
    MUX_PAD_CSI_VSYNC__GPIO4_IO19 = ALT5,
    MUX_PAD_CSI_VSYNC__PWM7_OUT = ALT6,
    MUX_PAD_CSI_VSYNC__UART6_RTS_B = ALT8,
    MUX_PAD_CSI_VSYNC__ESAI_TX4_RX1 = ALT9
};

enum MUX_PAD_ENET1_RX_DATA0 {
    MUX_PAD_ENET1_RX_DATA0__ENET1_RDATA00 = ALT0,
    MUX_PAD_ENET1_RX_DATA0__UART4_RTS_B = ALT1,
    MUX_PAD_ENET1_RX_DATA0__PWM1_OUT = ALT2,
    MUX_PAD_ENET1_RX_DATA0__CSI_DATA16 = ALT3,
    MUX_PAD_ENET1_RX_DATA0__FLEXCAN1_TX = ALT4,
    MUX_PAD_ENET1_RX_DATA0__GPIO2_IO00 = ALT5,
    MUX_PAD_ENET1_RX_DATA0__KPP_ROW00 = ALT6,
    MUX_PAD_ENET1_RX_DATA0__USDHC1_LCTL = ALT8,
    MUX_PAD_ENET1_RX_DATA0__EPDC_SDCE04 = ALT9
};

enum MUX_PAD_ENET1_RX_DATA1 {
    MUX_PAD_ENET1_RX_DATA1__ENET1_RDATA01 = ALT0,
    MUX_PAD_ENET1_RX_DATA1__UART4_CTS_B = ALT1,
    MUX_PAD_ENET1_RX_DATA1__PWM2_OUT = ALT2,
    MUX_PAD_ENET1_RX_DATA1__CSI_DATA17 = ALT3,
    MUX_PAD_ENET1_RX_DATA1__FLEXCAN1_RX = ALT4,
    MUX_PAD_ENET1_RX_DATA1__GPIO2_IO01 = ALT5,
    MUX_PAD_ENET1_RX_DATA1__KPP_COL00 = ALT6,
    MUX_PAD_ENET1_RX_DATA1__USDHC2_LCTL = ALT8,
    MUX_PAD_ENET1_RX_DATA1__EPDC_SDCE05 = ALT9
};

enum MUX_PAD_ENET1_RX_EN {
    MUX_PAD_ENET1_RX_EN__ENET1_RX_EN = ALT0,
    MUX_PAD_ENET1_RX_EN__UART5_RTS_B = ALT1,
    MUX_PAD_ENET1_RX_EN__CSI_DATA18 = ALT3,
    MUX_PAD_ENET1_RX_EN__FLEXCAN2_TX = ALT4,
    MUX_PAD_ENET1_RX_EN__GPIO2_IO02 = ALT5,
    MUX_PAD_ENET1_RX_EN__KPP_ROW01 = ALT6,
    MUX_PAD_ENET1_RX_EN__USDHC1_VSELECT = ALT8,
    MUX_PAD_ENET1_RX_EN__EPDC_SDCE06 = ALT9
};

enum MUX_PAD_ENET1_RX_ER {
    MUX_PAD_ENET1_RX_ER__ENET1_RX_ER = ALT0,
    MUX_PAD_ENET1_RX_ER__UART7_RTS_B = ALT1,
    MUX_PAD_ENET1_RX_ER__PWM8_OUT = ALT2,
    MUX_PAD_ENET1_RX_ER__CSI_DATA23 = ALT3,
    MUX_PAD_ENET1_RX_ER__EIM_CRE = ALT4,
    MUX_PAD_ENET1_RX_ER__GPIO2_IO07 = ALT5,
    MUX_PAD_ENET1_RX_ER__KPP_COL03 = ALT6,
    MUX_PAD_ENET1_RX_ER__GPT1_CAPTURE2 = ALT8,
    MUX_PAD_ENET1_RX_ER__EPDC_SDOEZ = ALT9
};

enum MUX_PAD_ENET1_TX_CLK {
    MUX_PAD_ENET1_TX_CLK__ENET1_TX_CLK = ALT0,
    MUX_PAD_ENET1_TX_CLK__UART7_CTS_B = ALT1,
    MUX_PAD_ENET1_TX_CLK__PWM7_OUT = ALT2,
    MUX_PAD_ENET1_TX_CLK__CSI_DATA22 = ALT3,
    MUX_PAD_ENET1_TX_CLK__ENET1_REF_CLK1 = ALT4,
    MUX_PAD_ENET1_TX_CLK__GPIO2_IO06 = ALT5,
    MUX_PAD_ENET1_TX_CLK__KPP_ROW03 = ALT6,
    MUX_PAD_ENET1_TX_CLK__GPT1_CLK = ALT8,
    MUX_PAD_ENET1_TX_CLK__EPDC_SDOED = ALT9
};

enum MUX_PAD_ENET1_TX_DATA0 {
    MUX_PAD_ENET1_TX_DATA0__ENET1_TDATA00 = ALT0,
    MUX_PAD_ENET1_TX_DATA0__UART5_CTS_B = ALT1,
    MUX_PAD_ENET1_TX_DATA0__CSI_DATA19 = ALT3,
    MUX_PAD_ENET1_TX_DATA0__FLEXCAN2_RX = ALT4,
    MUX_PAD_ENET1_TX_DATA0__GPIO2_IO03 = ALT5,
    MUX_PAD_ENET1_TX_DATA0__KPP_COL01 = ALT6,
    MUX_PAD_ENET1_TX_DATA0__USDHC2_VSELECT = ALT8,
    MUX_PAD_ENET1_TX_DATA0__EPDC_SDCE07 = ALT9
};

enum MUX_PAD_ENET1_TX_DATA1 {
    MUX_PAD_ENET1_TX_DATA1__ENET1_TDATA01 = ALT0,
    MUX_PAD_ENET1_TX_DATA1__UART6_CTS_B = ALT1,
    MUX_PAD_ENET1_TX_DATA1__PWM5_OUT = ALT2,
    MUX_PAD_ENET1_TX_DATA1__CSI_DATA20 = ALT3,
    MUX_PAD_ENET1_TX_DATA1__ENET2_MDIO = ALT4,
    MUX_PAD_ENET1_TX_DATA1__GPIO2_IO04 = ALT5,
    MUX_PAD_ENET1_TX_DATA1__KPP_ROW02 = ALT6,
    MUX_PAD_ENET1_TX_DATA1__WDOG1_WDOG_RST_B_DEB = ALT8,
    MUX_PAD_ENET1_TX_DATA1__EPDC_SDCE08 = ALT9
};

enum MUX_PAD_ENET1_TX_EN {
    MUX_PAD_ENET1_TX_EN__ENET1_TX_EN = ALT0,
    MUX_PAD_ENET1_TX_EN__UART6_RTS_B = ALT1,
    MUX_PAD_ENET1_TX_EN__PWM6_OUT = ALT2,
    MUX_PAD_ENET1_TX_EN__CSI_DATA21 = ALT3,
    MUX_PAD_ENET1_TX_EN__ENET2_MDC = ALT4,
    MUX_PAD_ENET1_TX_EN__GPIO2_IO05 = ALT5,
    MUX_PAD_ENET1_TX_EN__KPP_COL02 = ALT6,
    MUX_PAD_ENET1_TX_EN__WDOG2_WDOG_RST_B_DEB = ALT8,
    MUX_PAD_ENET1_TX_EN__EPDC_SDCE09 = ALT9
};

enum MUX_PAD_ENET2_RX_DATA0 {
    MUX_PAD_ENET2_RX_DATA0__ENET2_RDATA00 = ALT0,
    MUX_PAD_ENET2_RX_DATA0__UART6_TX = ALT1,
    MUX_PAD_ENET2_RX_DATA0__RESERVED_ALT2 = ALT2,
    MUX_PAD_ENET2_RX_DATA0__I2C3_SCL = ALT3,
    MUX_PAD_ENET2_RX_DATA0__ENET1_MDIO = ALT4,
    MUX_PAD_ENET2_RX_DATA0__GPIO2_IO08 = ALT5,
    MUX_PAD_ENET2_RX_DATA0__KPP_ROW04 = ALT6,
    MUX_PAD_ENET2_RX_DATA0__USB_OTG1_PWR = ALT8,
    MUX_PAD_ENET2_RX_DATA0__EPDC_SDDO08 = ALT9
};

enum MUX_PAD_ENET2_RX_DATA1 {
    MUX_PAD_ENET2_RX_DATA1__ENET2_RDATA01 = ALT0,
    MUX_PAD_ENET2_RX_DATA1__UART6_RX = ALT1,
    MUX_PAD_ENET2_RX_DATA1__RESERVED_ALT2 = ALT2,
    MUX_PAD_ENET2_RX_DATA1__I2C3_SDA = ALT3,
    MUX_PAD_ENET2_RX_DATA1__ENET1_MDC = ALT4,
    MUX_PAD_ENET2_RX_DATA1__GPIO2_IO09 = ALT5,
    MUX_PAD_ENET2_RX_DATA1__KPP_COL04 = ALT6,
    MUX_PAD_ENET2_RX_DATA1__USB_OTG1_OC = ALT8,
    MUX_PAD_ENET2_RX_DATA1__EPDC_SDDO09 = ALT9
};

enum MUX_PAD_ENET2_RX_EN {
    MUX_PAD_ENET2_RX_EN__ENET2_RX_EN = ALT0,
    MUX_PAD_ENET2_RX_EN__UART7_TX = ALT1,
    MUX_PAD_ENET2_RX_EN__RESERVED_ALT2 = ALT2,
    MUX_PAD_ENET2_RX_EN__I2C4_SCL = ALT3,
    MUX_PAD_ENET2_RX_EN__EIM_ADDR26 = ALT4,
    MUX_PAD_ENET2_RX_EN__GPIO2_IO10 = ALT5,
    MUX_PAD_ENET2_RX_EN__KPP_ROW05 = ALT6,
    MUX_PAD_ENET2_RX_EN__ENET1_REF_CLK_25M = ALT8,
    MUX_PAD_ENET2_RX_EN__EPDC_SDDO10 = ALT9
};

enum MUX_PAD_ENET2_RX_ER {
    MUX_PAD_ENET2_RX_ER__ENET2_RX_ER = ALT0,
    MUX_PAD_ENET2_RX_ER__UART8_RTS_B = ALT1,
    MUX_PAD_ENET2_RX_ER__RESERVED_ALT2 = ALT2,
    MUX_PAD_ENET2_RX_ER__ECSPI4_SS0 = ALT3,
    MUX_PAD_ENET2_RX_ER__EIM_ADDR25 = ALT4,
    MUX_PAD_ENET2_RX_ER__GPIO2_IO15 = ALT5,
    MUX_PAD_ENET2_RX_ER__KPP_COL07 = ALT6,
    MUX_PAD_ENET2_RX_ER__WDOG1_WDOG_ANY = ALT8,
    MUX_PAD_ENET2_RX_ER__EPDC_SDDO15 = ALT9
};

enum MUX_PAD_ENET2_TX_CLK {
    MUX_PAD_ENET2_TX_CLK__ENET2_TX_CLK = ALT0,
    MUX_PAD_ENET2_TX_CLK__UART8_CTS_B = ALT1,
    MUX_PAD_ENET2_TX_CLK__RESERVED_ALT2 = ALT2,
    MUX_PAD_ENET2_TX_CLK__ECSPI4_MISO = ALT3,
    MUX_PAD_ENET2_TX_CLK__ENET2_REF_CLK2 = ALT4,
    MUX_PAD_ENET2_TX_CLK__GPIO2_IO14 = ALT5,
    MUX_PAD_ENET2_TX_CLK__KPP_ROW07 = ALT6,
    MUX_PAD_ENET2_TX_CLK__ANATOP_OTG2_ID = ALT8,
    MUX_PAD_ENET2_TX_CLK__EPDC_SDDO14 = ALT9
};

enum MUX_PAD_ENET2_TX_DATA0 {
    MUX_PAD_ENET2_TX_DATA0__ENET2_TDATA00 = ALT0,
    MUX_PAD_ENET2_TX_DATA0__UART7_RX = ALT1,
    MUX_PAD_ENET2_TX_DATA0__RESERVED_ALT2 = ALT2,
    MUX_PAD_ENET2_TX_DATA0__I2C4_SDA = ALT3,
    MUX_PAD_ENET2_TX_DATA0__EIM_EB_B02 = ALT4,
    MUX_PAD_ENET2_TX_DATA0__GPIO2_IO11 = ALT5,
    MUX_PAD_ENET2_TX_DATA0__KPP_COL05 = ALT6,
    MUX_PAD_ENET2_TX_DATA0__EPDC_SDDO11 = ALT9
};

enum MUX_PAD_ENET2_TX_DATA1 {
    MUX_PAD_ENET2_TX_DATA1__ENET2_TDATA01 = ALT0,
    MUX_PAD_ENET2_TX_DATA1__UART8_TX = ALT1,
    MUX_PAD_ENET2_TX_DATA1__RESERVED_ALT2 = ALT2,
    MUX_PAD_ENET2_TX_DATA1__ECSPI4_SCLK = ALT3,
    MUX_PAD_ENET2_TX_DATA1__EIM_EB_B03 = ALT4,
    MUX_PAD_ENET2_TX_DATA1__GPIO2_IO12 = ALT5,
    MUX_PAD_ENET2_TX_DATA1__KPP_ROW06 = ALT6,
    MUX_PAD_ENET2_TX_DATA1__USB_OTG2_PWR = ALT8,
    MUX_PAD_ENET2_TX_DATA1__EPDC_SDDO12 = ALT9
};

enum MUX_PAD_ENET2_TX_EN {
    MUX_PAD_ENET2_TX_EN__ENET2_TX_EN = ALT0,
    MUX_PAD_ENET2_TX_EN__UART8_RX = ALT1,
    MUX_PAD_ENET2_TX_EN__RESERVED_ALT2 = ALT2,
    MUX_PAD_ENET2_TX_EN__ECSPI4_MOSI = ALT3,
    MUX_PAD_ENET2_TX_EN__EIM_ACLK_FREERUN = ALT4,
    MUX_PAD_ENET2_TX_EN__GPIO2_IO13 = ALT5,
    MUX_PAD_ENET2_TX_EN__KPP_COL06 = ALT6,
    MUX_PAD_ENET2_TX_EN__USB_OTG2_OC = ALT8,
    MUX_PAD_ENET2_TX_EN__EPDC_SDDO13 = ALT9
};

enum MUX_PAD_GPIO1_IO00 {
    MUX_PAD_GPIO1_IO00__I2C2_SCL = ALT0,
    MUX_PAD_GPIO1_IO00__GPT1_CAPTURE1 = ALT1,
    MUX_PAD_GPIO1_IO00__ANATOP_OTG1_ID = ALT2,
    MUX_PAD_GPIO1_IO00__ENET1_REF_CLK1 = ALT3,
    MUX_PAD_GPIO1_IO00__MQS_RIGHT = ALT4,
    MUX_PAD_GPIO1_IO00__GPIO1_IO00 = ALT5,
    MUX_PAD_GPIO1_IO00__ENET1_1588_EVENT0_IN = ALT6,
    MUX_PAD_GPIO1_IO00__SRC_SYSTEM_RESET = ALT7,
    MUX_PAD_GPIO1_IO00__WDOG3_WDOG_B = ALT8
};

enum MUX_PAD_GPIO1_IO02 {
    MUX_PAD_GPIO1_IO02__I2C1_SCL = ALT0,
    MUX_PAD_GPIO1_IO02__GPT1_COMPARE2 = ALT1,
    MUX_PAD_GPIO1_IO02__USB_OTG2_PWR = ALT2,
    MUX_PAD_GPIO1_IO02__ENET1_REF_CLK_25M = ALT3,
    MUX_PAD_GPIO1_IO02__USDHC1_WP = ALT4,
    MUX_PAD_GPIO1_IO02__GPIO1_IO02 = ALT5
};

enum MUX_PAD_GPIO1_IO03 {
    MUX_PAD_GPIO1_IO03__I2C1_SDA = ALT0,
    MUX_PAD_GPIO1_IO03__GPT1_COMPARE3 = ALT1,
    MUX_PAD_GPIO1_IO03__USB_OTG2_OC = ALT2,
    MUX_PAD_GPIO1_IO03__USDHC1_CD_B = ALT4,
    MUX_PAD_GPIO1_IO03__GPIO1_IO03 = ALT5,
    MUX_PAD_GPIO1_IO03__CCM_DI0_EXT_CLK = ALT6,
    MUX_PAD_GPIO1_IO03__SRC_TESTER_ACK = ALT7,
    MUX_PAD_GPIO1_IO03__UART1_RX = ALT8
};

enum MUX_PAD_GPIO1_IO04 {
    MUX_PAD_GPIO1_IO04__ENET1_REF_CLK1 = ALT0,
    MUX_PAD_GPIO1_IO04__PWM3_OUT = ALT1,
    MUX_PAD_GPIO1_IO04__USB_OTG1_PWR = ALT2,
    MUX_PAD_GPIO1_IO04__USDHC1_RESET_B = ALT4,
    MUX_PAD_GPIO1_IO04__GPIO1_IO04 = ALT5,
    MUX_PAD_GPIO1_IO04__ENET2_1588_EVENT0_IN = ALT6,
    MUX_PAD_GPIO1_IO04__UART5_TX = ALT8
};

enum MUX_PAD_GPIO1_IO05 {
    MUX_PAD_GPIO1_IO05__ENET2_REF_CLK2 = ALT0,
    MUX_PAD_GPIO1_IO05__PWM4_OUT = ALT1,
    MUX_PAD_GPIO1_IO05__ANATOP_OTG2_ID = ALT2,
    MUX_PAD_GPIO1_IO05__CSI_FIELD = ALT3,
    MUX_PAD_GPIO1_IO05__USDHC1_VSELECT = ALT4,
    MUX_PAD_GPIO1_IO05__GPIO1_IO05 = ALT5,
    MUX_PAD_GPIO1_IO05__ENET2_1588_EVENT0_OUT = ALT6,
    MUX_PAD_GPIO1_IO05__UART5_RX = ALT8
};

enum MUX_PAD_GPIO1_IO06 {
    MUX_PAD_GPIO1_IO06__ENET1_MDIO = ALT0,
    MUX_PAD_GPIO1_IO06__ENET2_MDIO = ALT1,
    MUX_PAD_GPIO1_IO06__USB_OTG_PWR_WAKE = ALT2,
    MUX_PAD_GPIO1_IO06__CSI_MCLK = ALT3,
    MUX_PAD_GPIO1_IO06__USDHC2_WP = ALT4,
    MUX_PAD_GPIO1_IO06__GPIO1_IO06 = ALT5,
    MUX_PAD_GPIO1_IO06__CCM_WAIT = ALT6,
    MUX_PAD_GPIO1_IO06__CCM_REF_EN_B = ALT7,
    MUX_PAD_GPIO1_IO06__UART1_CTS_B = ALT8
};

enum MUX_PAD_GPIO1_IO07 {
    MUX_PAD_GPIO1_IO07__ENET1_MDC = ALT0,
    MUX_PAD_GPIO1_IO07__ENET2_MDC = ALT1,
    MUX_PAD_GPIO1_IO07__USB_OTG_HOST_MODE = ALT2,
    MUX_PAD_GPIO1_IO07__CSI_PIXCLK = ALT3,
    MUX_PAD_GPIO1_IO07__USDHC2_CD_B = ALT4,
    MUX_PAD_GPIO1_IO07__GPIO1_IO07 = ALT5,
    MUX_PAD_GPIO1_IO07__CCM_STOP = ALT6,
    MUX_PAD_GPIO1_IO07__UART1_RTS_B = ALT8
};

enum MUX_PAD_GPIO1_IO08 {
    MUX_PAD_GPIO1_IO08__PWM1_OUT = ALT0,
    MUX_PAD_GPIO1_IO08__WDOG1_WDOG_B = ALT1,
    MUX_PAD_GPIO1_IO08__SPDIF_OUT = ALT2,
    MUX_PAD_GPIO1_IO08__CSI_VSYNC = ALT3,
    MUX_PAD_GPIO1_IO08__USDHC2_VSELECT = ALT4,
    MUX_PAD_GPIO1_IO08__GPIO1_IO08 = ALT5,
    MUX_PAD_GPIO1_IO08__CCM_PMIC_RDY = ALT6,
    MUX_PAD_GPIO1_IO08__UART5_RTS_B = ALT8
};

enum MUX_PAD_GPIO1_IO09 {
    MUX_PAD_GPIO1_IO09__PWM2_OUT = ALT0,
    MUX_PAD_GPIO1_IO09__WDOG1_WDOG_ANY = ALT1,
    MUX_PAD_GPIO1_IO09__SPDIF_IN = ALT2,
    MUX_PAD_GPIO1_IO09__CSI_HSYNC = ALT3,
    MUX_PAD_GPIO1_IO09__USDHC2_RESET_B = ALT4,
    MUX_PAD_GPIO1_IO09__GPIO1_IO09 = ALT5,
    MUX_PAD_GPIO1_IO09__USDHC1_RESET_B = ALT6,
    MUX_PAD_GPIO1_IO09__UART5_CTS_B = ALT8
};

enum MUX_PAD_JTAG_TCK {
    MUX_PAD_JTAG_TCK__SJC_TCK = ALT0,
    MUX_PAD_JTAG_TCK__GPT2_COMPARE2 = ALT1,
    MUX_PAD_JTAG_TCK__SAI2_RX_DATA = ALT2,
    MUX_PAD_JTAG_TCK__PWM7_OUT = ALT4,
    MUX_PAD_JTAG_TCK__GPIO1_IO14 = ALT5,
    MUX_PAD_JTAG_TCK__SIM2_POWER_FAIL = ALT8
};

enum MUX_PAD_JTAG_TDO {
    MUX_PAD_JTAG_TDO__SJC_TDO = ALT0,
    MUX_PAD_JTAG_TDO__GPT2_CAPTURE2 = ALT1,
    MUX_PAD_JTAG_TDO__SAI2_TX_SYNC = ALT2,
    MUX_PAD_JTAG_TDO__CCM_CLKO2 = ALT3,
    MUX_PAD_JTAG_TDO__CCM_STOP = ALT4,
    MUX_PAD_JTAG_TDO__GPIO1_IO12 = ALT5,
    MUX_PAD_JTAG_TDO__MQS_RIGHT = ALT6,
    MUX_PAD_JTAG_TDO__EPIT2_OUT = ALT8
};

enum MUX_PAD_JTAG_TMS {
    MUX_PAD_JTAG_TMS__SJC_TMS = ALT0,
    MUX_PAD_JTAG_TMS__GPT2_CAPTURE1 = ALT1,
    MUX_PAD_JTAG_TMS__SAI2_MCLK = ALT2,
    MUX_PAD_JTAG_TMS__CCM_CLKO1 = ALT3,
    MUX_PAD_JTAG_TMS__CCM_WAIT = ALT4,
    MUX_PAD_JTAG_TMS__GPIO1_IO11 = ALT5,
    MUX_PAD_JTAG_TMS__SDMA_EXT_EVENT01 = ALT6,
    MUX_PAD_JTAG_TMS__EPIT1_OUT = ALT8
};

enum MUX_PAD_JTAG_TRST_B {
    MUX_PAD_JTAG_TRST_B__SJC_TRSTB = ALT0,
    MUX_PAD_JTAG_TRST_B__GPT2_COMPARE3 = ALT1,
    MUX_PAD_JTAG_TRST_B__SAI2_TX_DATA = ALT2,
    MUX_PAD_JTAG_TRST_B__PWM8_OUT = ALT4,
    MUX_PAD_JTAG_TRST_B__GPIO1_IO15 = ALT5,
    MUX_PAD_JTAG_TRST_B__CAAM_RNG_OSC_OBS = ALT8
};

enum MUX_PAD_LCD_CLK {
    MUX_PAD_LCD_CLK__LCDIF_CLK = ALT0,
    MUX_PAD_LCD_CLK__LCDIF_WR_RWN = ALT1,
    MUX_PAD_LCD_CLK__UART4_TX = ALT2,
    MUX_PAD_LCD_CLK__SAI3_MCLK = ALT3,
    MUX_PAD_LCD_CLK__EIM_CS2_B = ALT4,
    MUX_PAD_LCD_CLK__GPIO3_IO00 = ALT5,
    MUX_PAD_LCD_CLK__WDOG1_WDOG_RST_B_DEB = ALT8,
    MUX_PAD_LCD_CLK__EPDC_SDCLK = ALT9
};

enum MUX_PAD_LCD_DATA00 {
    MUX_PAD_LCD_DATA00__LCDIF_DATA00 = ALT0,
    MUX_PAD_LCD_DATA00__PWM1_OUT = ALT1,
    MUX_PAD_LCD_DATA00__ENET1_1588_EVENT2_IN = ALT3,
    MUX_PAD_LCD_DATA00__I2C3_SDA = ALT4,
    MUX_PAD_LCD_DATA00__GPIO3_IO05 = ALT5,
    MUX_PAD_LCD_DATA00__SRC_BT_CFG00 = ALT6,
    MUX_PAD_LCD_DATA00__SAI1_MCLK = ALT8,
    MUX_PAD_LCD_DATA00__EPDC_SDDO00 = ALT9
};

enum MUX_PAD_LCD_DATA01 {
    MUX_PAD_LCD_DATA01__LCDIF_DATA01 = ALT0,
    MUX_PAD_LCD_DATA01__PWM2_OUT = ALT1,
    MUX_PAD_LCD_DATA01__ENET1_1588_EVENT2_OUT = ALT3,
    MUX_PAD_LCD_DATA01__I2C3_SCL = ALT4,
    MUX_PAD_LCD_DATA01__GPIO3_IO06 = ALT5,
    MUX_PAD_LCD_DATA01__SRC_BT_CFG01 = ALT6,
    MUX_PAD_LCD_DATA01__SAI1_TX_SYNC = ALT8,
    MUX_PAD_LCD_DATA01__EPDC_SDDO01 = ALT9
};

enum MUX_PAD_LCD_DATA02 {
    MUX_PAD_LCD_DATA02__LCDIF_DATA02 = ALT0,
    MUX_PAD_LCD_DATA02__PWM3_OUT = ALT1,
    MUX_PAD_LCD_DATA02__ENET1_1588_EVENT3_IN = ALT3,
    MUX_PAD_LCD_DATA02__I2C4_SDA = ALT4,
    MUX_PAD_LCD_DATA02__GPIO3_IO07 = ALT5,
    MUX_PAD_LCD_DATA02__SRC_BT_CFG02 = ALT6,
    MUX_PAD_LCD_DATA02__SAI1_TX_BCLK = ALT8,
    MUX_PAD_LCD_DATA02__EPDC_SDDO02 = ALT9
};

enum MUX_PAD_LCD_DATA03 {
    MUX_PAD_LCD_DATA03__LCDIF_DATA03 = ALT0,
    MUX_PAD_LCD_DATA03__PWM4_OUT = ALT1,
    MUX_PAD_LCD_DATA03__ENET1_1588_EVENT3_OUT = ALT3,
    MUX_PAD_LCD_DATA03__I2C4_SCL = ALT4,
    MUX_PAD_LCD_DATA03__GPIO3_IO08 = ALT5,
    MUX_PAD_LCD_DATA03__SRC_BT_CFG03 = ALT6,
    MUX_PAD_LCD_DATA03__SAI1_RX_DATA = ALT8,
    MUX_PAD_LCD_DATA03__EPDC_SDDO03 = ALT9
};

enum MUX_PAD_LCD_DATA04 {
    MUX_PAD_LCD_DATA04__LCDIF_DATA04 = ALT0,
    MUX_PAD_LCD_DATA04__UART8_CTS_B = ALT1,
    MUX_PAD_LCD_DATA04__ENET2_1588_EVENT2_IN = ALT3,
    MUX_PAD_LCD_DATA04__SPDIF_SR_CLK = ALT4,
    MUX_PAD_LCD_DATA04__GPIO3_IO09 = ALT5,
    MUX_PAD_LCD_DATA04__SRC_BT_CFG04 = ALT6,
    MUX_PAD_LCD_DATA04__SAI1_TX_DATA = ALT8,
    MUX_PAD_LCD_DATA04__EPDC_SDDO04 = ALT9
};

enum MUX_PAD_LCD_DATA05 {
    MUX_PAD_LCD_DATA05__LCDIF_DATA05 = ALT0,
    MUX_PAD_LCD_DATA05__UART8_RTS_B = ALT1,
    MUX_PAD_LCD_DATA05__ENET2_1588_EVENT2_OUT = ALT3,
    MUX_PAD_LCD_DATA05__SPDIF_OUT = ALT4,
    MUX_PAD_LCD_DATA05__GPIO3_IO10 = ALT5,
    MUX_PAD_LCD_DATA05__SRC_BT_CFG05 = ALT6,
    MUX_PAD_LCD_DATA05__ECSPI1_SS1 = ALT8,
    MUX_PAD_LCD_DATA05__EPDC_SDDO05 = ALT9
};

enum MUX_PAD_LCD_DATA06 {
    MUX_PAD_LCD_DATA06__LCDIF_DATA06 = ALT0,
    MUX_PAD_LCD_DATA06__UART7_CTS_B = ALT1,
    MUX_PAD_LCD_DATA06__ENET2_1588_EVENT3_IN = ALT3,
    MUX_PAD_LCD_DATA06__SPDIF_LOCK = ALT4,
    MUX_PAD_LCD_DATA06__GPIO3_IO11 = ALT5,
    MUX_PAD_LCD_DATA06__SRC_BT_CFG06 = ALT6,
    MUX_PAD_LCD_DATA06__ECSPI1_SS2 = ALT8,
    MUX_PAD_LCD_DATA06__EPDC_SDDO06 = ALT9
};

enum MUX_PAD_LCD_DATA07 {
    MUX_PAD_LCD_DATA07__LCDIF_DATA07 = ALT0,
    MUX_PAD_LCD_DATA07__UART7_RTS_B = ALT1,
    MUX_PAD_LCD_DATA07__ENET2_1588_EVENT3_OUT = ALT3,
    MUX_PAD_LCD_DATA07__SPDIF_EXT_CLK = ALT4,
    MUX_PAD_LCD_DATA07__GPIO3_IO12 = ALT5,
    MUX_PAD_LCD_DATA07__SRC_BT_CFG07 = ALT6,
    MUX_PAD_LCD_DATA07__ECSPI1_SS3 = ALT8,
    MUX_PAD_LCD_DATA07__EPDC_SDDO07 = ALT9
};

enum MUX_PAD_LCD_DATA08 {
    MUX_PAD_LCD_DATA08__LCDIF_DATA08 = ALT0,
    MUX_PAD_LCD_DATA08__SPDIF_IN = ALT1,
    MUX_PAD_LCD_DATA08__CSI_DATA16 = ALT3,
    MUX_PAD_LCD_DATA08__EIM_DATA00 = ALT4,
    MUX_PAD_LCD_DATA08__GPIO3_IO13 = ALT5,
    MUX_PAD_LCD_DATA08__SRC_BT_CFG08 = ALT6,
    MUX_PAD_LCD_DATA08__FLEXCAN1_TX = ALT8,
    MUX_PAD_LCD_DATA08__EPDC_PWRIRQ = ALT9
};

enum MUX_PAD_LCD_DATA09 {
    MUX_PAD_LCD_DATA09__LCDIF_DATA09 = ALT0,
    MUX_PAD_LCD_DATA09__SAI3_MCLK = ALT1,
    MUX_PAD_LCD_DATA09__CSI_DATA17 = ALT3,
    MUX_PAD_LCD_DATA09__EIM_DATA01 = ALT4,
    MUX_PAD_LCD_DATA09__GPIO3_IO14 = ALT5,
    MUX_PAD_LCD_DATA09__SRC_BT_CFG09 = ALT6,
    MUX_PAD_LCD_DATA09__FLEXCAN1_RX = ALT8,
    MUX_PAD_LCD_DATA09__EPDC_PWRWAKE = ALT9
};

enum MUX_PAD_LCD_DATA10 {
    MUX_PAD_LCD_DATA10__LCDIF_DATA10 = ALT0,
    MUX_PAD_LCD_DATA10__SAI3_RX_SYNC = ALT1,
    MUX_PAD_LCD_DATA10__CSI_DATA18 = ALT3,
    MUX_PAD_LCD_DATA10__EIM_DATA02 = ALT4,
    MUX_PAD_LCD_DATA10__GPIO3_IO15 = ALT5,
    MUX_PAD_LCD_DATA10__SRC_BT_CFG10 = ALT6,
    MUX_PAD_LCD_DATA10__FLEXCAN2_TX = ALT8,
    MUX_PAD_LCD_DATA10__EPDC_PWRCOM = ALT9
};

enum MUX_PAD_LCD_DATA11 {
    MUX_PAD_LCD_DATA11__LCDIF_DATA11 = ALT0,
    MUX_PAD_LCD_DATA11__SAI3_RX_BCLK = ALT1,
    MUX_PAD_LCD_DATA11__CSI_DATA19 = ALT3,
    MUX_PAD_LCD_DATA11__EIM_DATA03 = ALT4,
    MUX_PAD_LCD_DATA11__GPIO3_IO16 = ALT5,
    MUX_PAD_LCD_DATA11__SRC_BT_CFG11 = ALT6,
    MUX_PAD_LCD_DATA11__FLEXCAN2_RX = ALT8,
    MUX_PAD_LCD_DATA11__EPDC_PWRSTAT = ALT9
};

enum MUX_PAD_LCD_DATA12 {
    MUX_PAD_LCD_DATA12__LCDIF_DATA12 = ALT0,
    MUX_PAD_LCD_DATA12__SAI3_TX_SYNC = ALT1,
    MUX_PAD_LCD_DATA12__CSI_DATA20 = ALT3,
    MUX_PAD_LCD_DATA12__EIM_DATA04 = ALT4,
    MUX_PAD_LCD_DATA12__GPIO3_IO17 = ALT5,
    MUX_PAD_LCD_DATA12__SRC_BT_CFG12 = ALT6,
    MUX_PAD_LCD_DATA12__ECSPI1_RDY = ALT8,
    MUX_PAD_LCD_DATA12__EPDC_PWRCTRL00 = ALT9
};

enum MUX_PAD_LCD_DATA13 {
    MUX_PAD_LCD_DATA13__LCDIF_DATA13 = ALT0,
    MUX_PAD_LCD_DATA13__SAI3_TX_BCLK = ALT1,
    MUX_PAD_LCD_DATA13__CSI_DATA21 = ALT3,
    MUX_PAD_LCD_DATA13__EIM_DATA05 = ALT4,
    MUX_PAD_LCD_DATA13__GPIO3_IO18 = ALT5,
    MUX_PAD_LCD_DATA13__SRC_BT_CFG13 = ALT6,
    MUX_PAD_LCD_DATA13__USDHC2_RESET_B = ALT8,
    MUX_PAD_LCD_DATA13__EPDC_BDR00 = ALT9
};

enum MUX_PAD_LCD_DATA14 {
    MUX_PAD_LCD_DATA14__LCDIF_DATA14 = ALT0,
    MUX_PAD_LCD_DATA14__SAI3_RX_DATA = ALT1,
    MUX_PAD_LCD_DATA14__CSI_DATA22 = ALT3,
    MUX_PAD_LCD_DATA14__EIM_DATA06 = ALT4,
    MUX_PAD_LCD_DATA14__GPIO3_IO19 = ALT5,
    MUX_PAD_LCD_DATA14__SRC_BT_CFG14 = ALT6,
    MUX_PAD_LCD_DATA14__USDHC2_DATA4 = ALT8,
    MUX_PAD_LCD_DATA14__EPDC_SDSHR = ALT9
};

enum MUX_PAD_LCD_DATA15 {
    MUX_PAD_LCD_DATA15__LCDIF_DATA15 = ALT0,
    MUX_PAD_LCD_DATA15__SAI3_TX_DATA = ALT1,
    MUX_PAD_LCD_DATA15__CSI_DATA23 = ALT3,
    MUX_PAD_LCD_DATA15__EIM_DATA07 = ALT4,
    MUX_PAD_LCD_DATA15__GPIO3_IO20 = ALT5,
    MUX_PAD_LCD_DATA15__SRC_BT_CFG15 = ALT6,
    MUX_PAD_LCD_DATA15__USDHC2_DATA5 = ALT8,
    MUX_PAD_LCD_DATA15__EPDC_GDRL = ALT9
};

enum MUX_PAD_LCD_DATA16 {
    MUX_PAD_LCD_DATA16__LCDIF_DATA16 = ALT0,
    MUX_PAD_LCD_DATA16__UART7_TX = ALT1,
    MUX_PAD_LCD_DATA16__CSI_DATA01 = ALT3,
    MUX_PAD_LCD_DATA16__EIM_DATA08 = ALT4,
    MUX_PAD_LCD_DATA16__GPIO3_IO21 = ALT5,
    MUX_PAD_LCD_DATA16__SRC_BT_CFG24 = ALT6,
    MUX_PAD_LCD_DATA16__USDHC2_DATA6 = ALT8,
    MUX_PAD_LCD_DATA16__EPDC_GDCLK = ALT9
};

enum MUX_PAD_LCD_DATA17 {
    MUX_PAD_LCD_DATA17__LCDIF_DATA17 = ALT0,
    MUX_PAD_LCD_DATA17__UART7_RX = ALT1,
    MUX_PAD_LCD_DATA17__CSI_DATA00 = ALT3,
    MUX_PAD_LCD_DATA17__EIM_DATA09 = ALT4,
    MUX_PAD_LCD_DATA17__GPIO3_IO22 = ALT5,
    MUX_PAD_LCD_DATA17__SRC_BT_CFG25 = ALT6,
    MUX_PAD_LCD_DATA17__USDHC2_DATA7 = ALT8,
    MUX_PAD_LCD_DATA17__EPDC_GDSP = ALT9
};

enum MUX_PAD_LCD_DATA18 {
    MUX_PAD_LCD_DATA18__LCDIF_DATA18 = ALT0,
    MUX_PAD_LCD_DATA18__PWM5_OUT = ALT1,
    MUX_PAD_LCD_DATA18__CA7_MX6ULL_EVENTO = ALT2,
    MUX_PAD_LCD_DATA18__CSI_DATA10 = ALT3,
    MUX_PAD_LCD_DATA18__EIM_DATA10 = ALT4,
    MUX_PAD_LCD_DATA18__GPIO3_IO23 = ALT5,
    MUX_PAD_LCD_DATA18__SRC_BT_CFG26 = ALT6,
    MUX_PAD_LCD_DATA18__USDHC2_CMD = ALT8,
    MUX_PAD_LCD_DATA18__EPDC_BDR01 = ALT9
};

enum MUX_PAD_LCD_DATA19 {
    MUX_PAD_LCD_DATA19__EIM_DATA11 = ALT4,
    MUX_PAD_LCD_DATA19__GPIO3_IO24 = ALT5,
    MUX_PAD_LCD_DATA19__SRC_BT_CFG27 = ALT6,
    MUX_PAD_LCD_DATA19__USDHC2_CLK = ALT8,
    MUX_PAD_LCD_DATA19__EPDC_VCOM00 = ALT9,
    MUX_PAD_LCD_DATA19__LCDIF_DATA19 = ALT0,
    MUX_PAD_LCD_DATA19__PWM6_OUT = ALT1,
    MUX_PAD_LCD_DATA19__WDOG1_WDOG_ANY = ALT2,
    MUX_PAD_LCD_DATA19__CSI_DATA11 = ALT3
};

enum MUX_PAD_LCD_DATA20 {
    MUX_PAD_LCD_DATA20__EIM_DATA12 = ALT4,
    MUX_PAD_LCD_DATA20__GPIO3_IO25 = ALT5,
    MUX_PAD_LCD_DATA20__SRC_BT_CFG28 = ALT6,
    MUX_PAD_LCD_DATA20__USDHC2_DATA0 = ALT8,
    MUX_PAD_LCD_DATA20__EPDC_VCOM01 = ALT9,
    MUX_PAD_LCD_DATA20__LCDIF_DATA20 = ALT0,
    MUX_PAD_LCD_DATA20__UART8_TX = ALT1,
    MUX_PAD_LCD_DATA20__ECSPI1_SCLK = ALT2,
    MUX_PAD_LCD_DATA20__CSI_DATA12 = ALT3
};

enum MUX_PAD_LCD_DATA21 {
    MUX_PAD_LCD_DATA21__LCDIF_DATA21 = ALT0,
    MUX_PAD_LCD_DATA21__UART8_RX = ALT1,
    MUX_PAD_LCD_DATA21__ECSPI1_SS0 = ALT2,
    MUX_PAD_LCD_DATA21__CSI_DATA13 = ALT3,
    MUX_PAD_LCD_DATA21__EIM_DATA13 = ALT4,
    MUX_PAD_LCD_DATA21__GPIO3_IO26 = ALT5,
    MUX_PAD_LCD_DATA21__SRC_BT_CFG29 = ALT6,
    MUX_PAD_LCD_DATA21__USDHC2_DATA1 = ALT8,
    MUX_PAD_LCD_DATA21__EPDC_SDCE01 = ALT9
};

enum MUX_PAD_LCD_DATA22 {
    MUX_PAD_LCD_DATA22__LCDIF_DATA22 = ALT0,
    MUX_PAD_LCD_DATA22__MQS_RIGHT = ALT1,
    MUX_PAD_LCD_DATA22__ECSPI1_MOSI = ALT2,
    MUX_PAD_LCD_DATA22__CSI_DATA14 = ALT3,
    MUX_PAD_LCD_DATA22__EIM_DATA14 = ALT4,
    MUX_PAD_LCD_DATA22__GPIO3_IO27 = ALT5,
    MUX_PAD_LCD_DATA22__SRC_BT_CFG30 = ALT6,
    MUX_PAD_LCD_DATA22__USDHC2_DATA2 = ALT8,
    MUX_PAD_LCD_DATA22__EPDC_SDCE02 = ALT9
};

enum MUX_PAD_LCD_DATA23 {
    MUX_PAD_LCD_DATA23__EPDC_SDCE03 = ALT9,
    MUX_PAD_LCD_DATA23__LCDIF_DATA23 = ALT0,
    MUX_PAD_LCD_DATA23__MQS_LEFT = ALT1,
    MUX_PAD_LCD_DATA23__ECSPI1_MISO = ALT2,
    MUX_PAD_LCD_DATA23__CSI_DATA15 = ALT3,
    MUX_PAD_LCD_DATA23__EIM_DATA15 = ALT4,
    MUX_PAD_LCD_DATA23__GPIO3_IO28 = ALT5,
    MUX_PAD_LCD_DATA23__SRC_BT_CFG31 = ALT6,
    MUX_PAD_LCD_DATA23__USDHC2_DATA3 = ALT8
};

enum MUX_PAD_LCD_ENABLE {
    MUX_PAD_LCD_ENABLE__LCDIF_ENABLE = ALT0,
    MUX_PAD_LCD_ENABLE__LCDIF_RD_E = ALT1,
    MUX_PAD_LCD_ENABLE__UART4_RX = ALT2,
    MUX_PAD_LCD_ENABLE__SAI3_TX_SYNC = ALT3,
    MUX_PAD_LCD_ENABLE__EIM_CS3_B = ALT4,
    MUX_PAD_LCD_ENABLE__GPIO3_IO01 = ALT5,
    MUX_PAD_LCD_ENABLE__ECSPI2_RDY = ALT8,
    MUX_PAD_LCD_ENABLE__EPDC_SDLE = ALT9
};

enum MUX_PAD_LCD_HSYNC {
    MUX_PAD_LCD_HSYNC__LCDIF_HSYNC = ALT0,
    MUX_PAD_LCD_HSYNC__LCDIF_RS = ALT1,
    MUX_PAD_LCD_HSYNC__UART4_CTS_B = ALT2,
    MUX_PAD_LCD_HSYNC__SAI3_TX_BCLK = ALT3,
    MUX_PAD_LCD_HSYNC__WDOG3_WDOG_RST_B_DEB = ALT4,
    MUX_PAD_LCD_HSYNC__GPIO3_IO02 = ALT5,
    MUX_PAD_LCD_HSYNC__ECSPI2_SS1 = ALT8,
    MUX_PAD_LCD_HSYNC__EPDC_SDOE = ALT9
};

enum MUX_PAD_LCD_RESET {
    MUX_PAD_LCD_RESET__LCDIF_RESET = ALT0,
    MUX_PAD_LCD_RESET__LCDIF_CS = ALT1,
    MUX_PAD_LCD_RESET__CA7_MX6ULL_EVENTI = ALT2,
    MUX_PAD_LCD_RESET__SAI3_TX_DATA = ALT3,
    MUX_PAD_LCD_RESET__WDOG1_WDOG_ANY = ALT4,
    MUX_PAD_LCD_RESET__GPIO3_IO04 = ALT5,
    MUX_PAD_LCD_RESET__ECSPI2_SS3 = ALT8,
    MUX_PAD_LCD_RESET__EPDC_GDOE = ALT9
};

enum MUX_PAD_LCD_VSYNC {
    MUX_PAD_LCD_VSYNC__LCDIF_VSYNC = ALT0,
    MUX_PAD_LCD_VSYNC__LCDIF_BUSY = ALT1,
    MUX_PAD_LCD_VSYNC__UART4_RTS_B = ALT2,
    MUX_PAD_LCD_VSYNC__SAI3_RX_DATA = ALT3,
    MUX_PAD_LCD_VSYNC__WDOG2_WDOG_B = ALT4,
    MUX_PAD_LCD_VSYNC__GPIO3_IO03 = ALT5,
    MUX_PAD_LCD_VSYNC__ECSPI2_SS2 = ALT8,
    MUX_PAD_LCD_VSYNC__EPDC_SDCE00 = ALT9
};

enum MUX_PAD_NAND_ALE {
    MUX_PAD_NAND_ALE__RAWNAND_ALE = ALT0,
    MUX_PAD_NAND_ALE__USDHC2_RESET_B = ALT1,
    MUX_PAD_NAND_ALE__QSPI_A_DQS = ALT2,
    MUX_PAD_NAND_ALE__PWM3_OUT = ALT3,
    MUX_PAD_NAND_ALE__EIM_ADDR17 = ALT4,
    MUX_PAD_NAND_ALE__GPIO4_IO10 = ALT5,
    MUX_PAD_NAND_ALE__ECSPI3_SS1 = ALT8
};

enum MUX_PAD_NAND_CE0_B {
    MUX_PAD_NAND_CE0_B__RAWNAND_CE0_B = ALT0,
    MUX_PAD_NAND_CE0_B__USDHC1_DATA5 = ALT1,
    MUX_PAD_NAND_CE0_B__QSPI_A_DATA01 = ALT2,
    MUX_PAD_NAND_CE0_B__ECSPI3_SCLK = ALT3,
    MUX_PAD_NAND_CE0_B__EIM_DTACK_B = ALT4,
    MUX_PAD_NAND_CE0_B__GPIO4_IO13 = ALT5,
    MUX_PAD_NAND_CE0_B__UART3_RX = ALT8
};

enum MUX_PAD_NAND_CE1_B {
    MUX_PAD_NAND_CE1_B__RAWNAND_CE1_B = ALT0,
    MUX_PAD_NAND_CE1_B__USDHC1_DATA6 = ALT1,
    MUX_PAD_NAND_CE1_B__QSPI_A_DATA02 = ALT2,
    MUX_PAD_NAND_CE1_B__ECSPI3_MOSI = ALT3,
    MUX_PAD_NAND_CE1_B__EIM_ADDR18 = ALT4,
    MUX_PAD_NAND_CE1_B__GPIO4_IO14 = ALT5,
    MUX_PAD_NAND_CE1_B__UART3_CTS_B = ALT8
};

enum MUX_PAD_NAND_CLE {
    MUX_PAD_NAND_CLE__RAWNAND_CLE = ALT0,
    MUX_PAD_NAND_CLE__USDHC1_DATA7 = ALT1,
    MUX_PAD_NAND_CLE__QSPI_A_DATA03 = ALT2,
    MUX_PAD_NAND_CLE__ECSPI3_MISO = ALT3,
    MUX_PAD_NAND_CLE__EIM_ADDR16 = ALT4,
    MUX_PAD_NAND_CLE__GPIO4_IO15 = ALT5,
    MUX_PAD_NAND_CLE__UART3_RTS_B = ALT8
};

enum MUX_PAD_NAND_DATA00 {
    MUX_PAD_NAND_DATA00__RAWNAND_DATA00 = ALT0,
    MUX_PAD_NAND_DATA00__USDHC2_DATA0 = ALT1,
    MUX_PAD_NAND_DATA00__QSPI_B_SS1_B = ALT2,
    MUX_PAD_NAND_DATA00__KPP_ROW01 = ALT3,
    MUX_PAD_NAND_DATA00__EIM_AD08 = ALT4,
    MUX_PAD_NAND_DATA00__GPIO4_IO02 = ALT5,
    MUX_PAD_NAND_DATA00__ECSPI4_RDY = ALT8
};

enum MUX_PAD_NAND_DATA01 {
    MUX_PAD_NAND_DATA01__RAWNAND_DATA01 = ALT0,
    MUX_PAD_NAND_DATA01__USDHC2_DATA1 = ALT1,
    MUX_PAD_NAND_DATA01__QSPI_B_DQS = ALT2,
    MUX_PAD_NAND_DATA01__KPP_COL01 = ALT3,
    MUX_PAD_NAND_DATA01__EIM_AD09 = ALT4,
    MUX_PAD_NAND_DATA01__GPIO4_IO03 = ALT5,
    MUX_PAD_NAND_DATA01__ECSPI4_SS1 = ALT8
};

enum MUX_PAD_NAND_DATA02 {
    MUX_PAD_NAND_DATA02__RAWNAND_DATA02 = ALT0,
    MUX_PAD_NAND_DATA02__USDHC2_DATA2 = ALT1,
    MUX_PAD_NAND_DATA02__QSPI_B_DATA00 = ALT2,
    MUX_PAD_NAND_DATA02__KPP_ROW02 = ALT3,
    MUX_PAD_NAND_DATA02__EIM_AD10 = ALT4,
    MUX_PAD_NAND_DATA02__GPIO4_IO04 = ALT5,
    MUX_PAD_NAND_DATA02__ECSPI4_SS2 = ALT8
};

enum MUX_PAD_NAND_DATA03 {
    MUX_PAD_NAND_DATA03__RAWNAND_DATA03 = ALT0,
    MUX_PAD_NAND_DATA03__USDHC2_DATA3 = ALT1,
    MUX_PAD_NAND_DATA03__QSPI_B_DATA01 = ALT2,
    MUX_PAD_NAND_DATA03__KPP_COL02 = ALT3,
    MUX_PAD_NAND_DATA03__EIM_AD11 = ALT4,
    MUX_PAD_NAND_DATA03__GPIO4_IO05 = ALT5,
    MUX_PAD_NAND_DATA03__ECSPI4_SS3 = ALT8
};

enum MUX_PAD_NAND_DATA04 {
    MUX_PAD_NAND_DATA04__RAWNAND_DATA04 = ALT0,
    MUX_PAD_NAND_DATA04__USDHC2_DATA4 = ALT1,
    MUX_PAD_NAND_DATA04__QSPI_B_DATA02 = ALT2,
    MUX_PAD_NAND_DATA04__ECSPI4_SCLK = ALT3,
    MUX_PAD_NAND_DATA04__EIM_AD12 = ALT4,
    MUX_PAD_NAND_DATA04__GPIO4_IO06 = ALT5,
    MUX_PAD_NAND_DATA04__UART2_TX = ALT8
};

enum MUX_PAD_NAND_DATA05 {
    MUX_PAD_NAND_DATA05__RAWNAND_DATA05 = ALT0,
    MUX_PAD_NAND_DATA05__USDHC2_DATA5 = ALT1,
    MUX_PAD_NAND_DATA05__QSPI_B_DATA03 = ALT2,
    MUX_PAD_NAND_DATA05__ECSPI4_MOSI = ALT3,
    MUX_PAD_NAND_DATA05__EIM_AD13 = ALT4,
    MUX_PAD_NAND_DATA05__GPIO4_IO07 = ALT5,
    MUX_PAD_NAND_DATA05__UART2_RX = ALT8
};

enum MUX_PAD_NAND_DATA06 {
    MUX_PAD_NAND_DATA06__RAWNAND_DATA06 = ALT0,
    MUX_PAD_NAND_DATA06__USDHC2_DATA6 = ALT1,
    MUX_PAD_NAND_DATA06__SAI2_RX_BCLK = ALT2,
    MUX_PAD_NAND_DATA06__ECSPI4_MISO = ALT3,
    MUX_PAD_NAND_DATA06__EIM_AD14 = ALT4,
    MUX_PAD_NAND_DATA06__GPIO4_IO08 = ALT5,
    MUX_PAD_NAND_DATA06__UART2_CTS_B = ALT8
};

enum MUX_PAD_NAND_DATA07 {
    MUX_PAD_NAND_DATA07__RAWNAND_DATA07 = ALT0,
    MUX_PAD_NAND_DATA07__USDHC2_DATA7 = ALT1,
    MUX_PAD_NAND_DATA07__QSPI_A_SS1_B = ALT2,
    MUX_PAD_NAND_DATA07__ECSPI4_SS0 = ALT3,
    MUX_PAD_NAND_DATA07__EIM_AD15 = ALT4,
    MUX_PAD_NAND_DATA07__GPIO4_IO09 = ALT5,
    MUX_PAD_NAND_DATA07__UART2_RTS_B = ALT8
};

enum MUX_PAD_NAND_DQS {
    MUX_PAD_NAND_DQS__RAWNAND_DQS = ALT0,
    MUX_PAD_NAND_DQS__CSI_FIELD = ALT1,
    MUX_PAD_NAND_DQS__QSPI_A_SS0_B = ALT2,
    MUX_PAD_NAND_DQS__PWM5_OUT = ALT3,
    MUX_PAD_NAND_DQS__EIM_WAIT = ALT4,
    MUX_PAD_NAND_DQS__GPIO4_IO16 = ALT5,
    MUX_PAD_NAND_DQS__SDMA_EXT_EVENT01 = ALT6,
    MUX_PAD_NAND_DQS__SPDIF_EXT_CLK = ALT8
};

enum MUX_PAD_NAND_READY_B {
    MUX_PAD_NAND_READY_B__RAWNAND_READY_B = ALT0,
    MUX_PAD_NAND_READY_B__USDHC1_DATA4 = ALT1,
    MUX_PAD_NAND_READY_B__QSPI_A_DATA00 = ALT2,
    MUX_PAD_NAND_READY_B__ECSPI3_SS0 = ALT3,
    MUX_PAD_NAND_READY_B__EIM_CS1_B = ALT4,
    MUX_PAD_NAND_READY_B__GPIO4_IO12 = ALT5,
    MUX_PAD_NAND_READY_B__UART3_TX = ALT8
};

enum MUX_PAD_NAND_RE_B {
    MUX_PAD_NAND_RE_B__RAWNAND_RE_B = ALT0,
    MUX_PAD_NAND_RE_B__USDHC2_CLK = ALT1,
    MUX_PAD_NAND_RE_B__QSPI_B_SCLK = ALT2,
    MUX_PAD_NAND_RE_B__KPP_ROW00 = ALT3,
    MUX_PAD_NAND_RE_B__EIM_EB_B00 = ALT4,
    MUX_PAD_NAND_RE_B__GPIO4_IO00 = ALT5,
    MUX_PAD_NAND_RE_B__ECSPI3_SS2 = ALT8
};

enum MUX_PAD_NAND_WE_B {
    MUX_PAD_NAND_WE_B__RAWNAND_WE_B = ALT0,
    MUX_PAD_NAND_WE_B__USDHC2_CMD = ALT1,
    MUX_PAD_NAND_WE_B__QSPI_B_SS0_B = ALT2,
    MUX_PAD_NAND_WE_B__KPP_COL00 = ALT3,
    MUX_PAD_NAND_WE_B__EIM_EB_B01 = ALT4,
    MUX_PAD_NAND_WE_B__GPIO4_IO01 = ALT5,
    MUX_PAD_NAND_WE_B__ECSPI3_SS3 = ALT8
};

enum MUX_PAD_NAND_WP_B {
    MUX_PAD_NAND_WP_B__RAWNAND_WP_B = ALT0,
    MUX_PAD_NAND_WP_B__USDHC1_RESET_B = ALT1,
    MUX_PAD_NAND_WP_B__QSPI_A_SCLK = ALT2,
    MUX_PAD_NAND_WP_B__PWM4_OUT = ALT3,
    MUX_PAD_NAND_WP_B__EIM_BCLK = ALT4,
    MUX_PAD_NAND_WP_B__GPIO4_IO11 = ALT5,
    MUX_PAD_NAND_WP_B__ECSPI3_RDY = ALT8
};

enum MUX_PAD_SD1_CLK {
    MUX_PAD_SD1_CLK__USDHC1_CLK = ALT0,
    MUX_PAD_SD1_CLK__GPT2_COMPARE2 = ALT1,
    MUX_PAD_SD1_CLK__SAI2_MCLK = ALT2,
    MUX_PAD_SD1_CLK__SPDIF_IN = ALT3,
    MUX_PAD_SD1_CLK__EIM_ADDR20 = ALT4,
    MUX_PAD_SD1_CLK__GPIO2_IO17 = ALT5,
    MUX_PAD_SD1_CLK__USB_OTG1_OC = ALT8
};

enum MUX_PAD_SD1_CMD {
    MUX_PAD_SD1_CMD__USDHC1_CMD = ALT0,
    MUX_PAD_SD1_CMD__GPT2_COMPARE1 = ALT1,
    MUX_PAD_SD1_CMD__SAI2_RX_SYNC = ALT2,
    MUX_PAD_SD1_CMD__SPDIF_OUT = ALT3,
    MUX_PAD_SD1_CMD__EIM_ADDR19 = ALT4,
    MUX_PAD_SD1_CMD__GPIO2_IO16 = ALT5,
    MUX_PAD_SD1_CMD__SDMA_EXT_EVENT00 = ALT6,
    MUX_PAD_SD1_CMD__USB_OTG1_PWR = ALT8
};

enum MUX_PAD_SD1_DATA0 {
    MUX_PAD_SD1_DATA0__USDHC1_DATA0 = ALT0,
    MUX_PAD_SD1_DATA0__GPT2_COMPARE3 = ALT1,
    MUX_PAD_SD1_DATA0__SAI2_TX_SYNC = ALT2,
    MUX_PAD_SD1_DATA0__FLEXCAN1_TX = ALT3,
    MUX_PAD_SD1_DATA0__EIM_ADDR21 = ALT4,
    MUX_PAD_SD1_DATA0__GPIO2_IO18 = ALT5,
    MUX_PAD_SD1_DATA0__ANATOP_OTG1_ID = ALT8
};

enum MUX_PAD_SD1_DATA1 {
    MUX_PAD_SD1_DATA1__USDHC1_DATA1 = ALT0,
    MUX_PAD_SD1_DATA1__GPT2_CLK = ALT1,
    MUX_PAD_SD1_DATA1__SAI2_TX_BCLK = ALT2,
    MUX_PAD_SD1_DATA1__FLEXCAN1_RX = ALT3,
    MUX_PAD_SD1_DATA1__EIM_ADDR22 = ALT4,
    MUX_PAD_SD1_DATA1__GPIO2_IO19 = ALT5,
    MUX_PAD_SD1_DATA1__USB_OTG2_PWR = ALT8
};

enum MUX_PAD_SD1_DATA2 {
    MUX_PAD_SD1_DATA2__USDHC1_DATA2 = ALT0,
    MUX_PAD_SD1_DATA2__GPT2_CAPTURE1 = ALT1,
    MUX_PAD_SD1_DATA2__SAI2_RX_DATA = ALT2,
    MUX_PAD_SD1_DATA2__FLEXCAN2_TX = ALT3,
    MUX_PAD_SD1_DATA2__EIM_ADDR23 = ALT4,
    MUX_PAD_SD1_DATA2__GPIO2_IO20 = ALT5,
    MUX_PAD_SD1_DATA2__CCM_CLKO1 = ALT6,
    MUX_PAD_SD1_DATA2__USB_OTG2_OC = ALT8
};

enum MUX_PAD_SD1_DATA3 {
    MUX_PAD_SD1_DATA3__USDHC1_DATA3 = ALT0,
    MUX_PAD_SD1_DATA3__GPT2_CAPTURE2 = ALT1,
    MUX_PAD_SD1_DATA3__SAI2_TX_DATA = ALT2,
    MUX_PAD_SD1_DATA3__FLEXCAN2_RX = ALT3,
    MUX_PAD_SD1_DATA3__EIM_ADDR24 = ALT4,
    MUX_PAD_SD1_DATA3__GPIO2_IO21 = ALT5,
    MUX_PAD_SD1_DATA3__CCM_CLKO2 = ALT6,
    MUX_PAD_SD1_DATA3__ANATOP_OTG2_ID = ALT8
};

enum MUX_PAD_UART1_CTS_B {
    MUX_PAD_UART1_CTS_B__UART1_CTS_B = ALT0,
    MUX_PAD_UART1_CTS_B__ENET1_RX_CLK = ALT1,
    MUX_PAD_UART1_CTS_B__USDHC1_WP = ALT2,
    MUX_PAD_UART1_CTS_B__CSI_DATA04 = ALT3,
    MUX_PAD_UART1_CTS_B__ENET2_1588_EVENT1_IN = ALT4,
    MUX_PAD_UART1_CTS_B__GPIO1_IO18 = ALT5,
    MUX_PAD_UART1_CTS_B__USDHC2_WP = ALT8,
    MUX_PAD_UART1_CTS_B__UART5_CTS_B = ALT9
};

enum MUX_PAD_UART1_RTS_B {
    MUX_PAD_UART1_RTS_B__UART1_RTS_B = ALT0,
    MUX_PAD_UART1_RTS_B__ENET1_TX_ER = ALT1,
    MUX_PAD_UART1_RTS_B__USDHC1_CD_B = ALT2,
    MUX_PAD_UART1_RTS_B__CSI_DATA05 = ALT3,
    MUX_PAD_UART1_RTS_B__ENET2_1588_EVENT1_OUT = ALT4,
    MUX_PAD_UART1_RTS_B__GPIO1_IO19 = ALT5,
    MUX_PAD_UART1_RTS_B__USDHC2_CD_B = ALT8,
    MUX_PAD_UART1_RTS_B__UART5_RTS_B = ALT9
};

enum MUX_PAD_UART1_RX_DATA {
    MUX_PAD_UART1_RX_DATA__UART1_RX = ALT0,
    MUX_PAD_UART1_RX_DATA__ENET1_RDATA03 = ALT1,
    MUX_PAD_UART1_RX_DATA__I2C3_SDA = ALT2,
    MUX_PAD_UART1_RX_DATA__CSI_DATA03 = ALT3,
    MUX_PAD_UART1_RX_DATA__GPT1_CLK = ALT4,
    MUX_PAD_UART1_RX_DATA__GPIO1_IO17 = ALT5,
    MUX_PAD_UART1_RX_DATA__SPDIF_IN = ALT8,
    MUX_PAD_UART1_RX_DATA__UART5_RX = ALT9
};

enum MUX_PAD_UART1_TX_DATA {
    MUX_PAD_UART1_TX_DATA__UART1_TX = ALT0,
    MUX_PAD_UART1_TX_DATA__ENET1_RDATA02 = ALT1,
    MUX_PAD_UART1_TX_DATA__I2C3_SCL = ALT2,
    MUX_PAD_UART1_TX_DATA__CSI_DATA02 = ALT3,
    MUX_PAD_UART1_TX_DATA__GPT1_COMPARE1 = ALT4,
    MUX_PAD_UART1_TX_DATA__GPIO1_IO16 = ALT5,
    MUX_PAD_UART1_TX_DATA__SPDIF_OUT = ALT8,
    MUX_PAD_UART1_TX_DATA__UART5_TX = ALT9
};

enum MUX_PAD_UART2_CTS_B {
    MUX_PAD_UART2_CTS_B__UART2_CTS_B = ALT0,
    MUX_PAD_UART2_CTS_B__ENET1_CRS = ALT1,
    MUX_PAD_UART2_CTS_B__FLEXCAN2_TX = ALT2,
    MUX_PAD_UART2_CTS_B__CSI_DATA08 = ALT3,
    MUX_PAD_UART2_CTS_B__GPT1_COMPARE2 = ALT4,
    MUX_PAD_UART2_CTS_B__GPIO1_IO22 = ALT5,
    MUX_PAD_UART2_CTS_B__SJC_DE_B = ALT7,
    MUX_PAD_UART2_CTS_B__ECSPI3_MOSI = ALT8
};

enum MUX_PAD_UART2_RTS_B {
    MUX_PAD_UART2_RTS_B__UART2_RTS_B = ALT0,
    MUX_PAD_UART2_RTS_B__ENET1_COL = ALT1,
    MUX_PAD_UART2_RTS_B__FLEXCAN2_RX = ALT2,
    MUX_PAD_UART2_RTS_B__CSI_DATA09 = ALT3,
    MUX_PAD_UART2_RTS_B__GPT1_COMPARE3 = ALT4,
    MUX_PAD_UART2_RTS_B__GPIO1_IO23 = ALT5,
    MUX_PAD_UART2_RTS_B__SJC_FAIL = ALT7,
    MUX_PAD_UART2_RTS_B__ECSPI3_MISO = ALT8
};

enum MUX_PAD_UART2_RX_DATA {
    MUX_PAD_UART2_RX_DATA__UART2_RX = ALT0,
    MUX_PAD_UART2_RX_DATA__ENET1_TDATA03 = ALT1,
    MUX_PAD_UART2_RX_DATA__I2C4_SDA = ALT2,
    MUX_PAD_UART2_RX_DATA__CSI_DATA07 = ALT3,
    MUX_PAD_UART2_RX_DATA__GPT1_CAPTURE2 = ALT4,
    MUX_PAD_UART2_RX_DATA__GPIO1_IO21 = ALT5,
    MUX_PAD_UART2_RX_DATA__SJC_DONE = ALT7,
    MUX_PAD_UART2_RX_DATA__ECSPI3_SCLK = ALT8
};

enum MUX_PAD_UART2_TX_DATA {
    MUX_PAD_UART2_TX_DATA__UART2_TX = ALT0,
    MUX_PAD_UART2_TX_DATA__ENET1_TDATA02 = ALT1,
    MUX_PAD_UART2_TX_DATA__I2C4_SCL = ALT2,
    MUX_PAD_UART2_TX_DATA__CSI_DATA06 = ALT3,
    MUX_PAD_UART2_TX_DATA__GPT1_CAPTURE1 = ALT4,
    MUX_PAD_UART2_TX_DATA__GPIO1_IO20 = ALT5,
    MUX_PAD_UART2_TX_DATA__ECSPI3_SS0 = ALT8
};

enum MUX_PAD_UART3_CTS_B {
    MUX_PAD_UART3_CTS_B__UART3_CTS_B = ALT0,
    MUX_PAD_UART3_CTS_B__ENET2_RX_CLK = ALT1,
    MUX_PAD_UART3_CTS_B__FLEXCAN1_TX = ALT2,
    MUX_PAD_UART3_CTS_B__CSI_DATA10 = ALT3,
    MUX_PAD_UART3_CTS_B__ENET1_1588_EVENT1_IN = ALT4,
    MUX_PAD_UART3_CTS_B__GPIO1_IO26 = ALT5,
    MUX_PAD_UART3_CTS_B__EPIT2_OUT = ALT8
};

enum MUX_PAD_UART3_RTS_B {
    MUX_PAD_UART3_RTS_B__UART3_RTS_B = ALT0,
    MUX_PAD_UART3_RTS_B__ENET2_TX_ER = ALT1,
    MUX_PAD_UART3_RTS_B__FLEXCAN1_RX = ALT2,
    MUX_PAD_UART3_RTS_B__CSI_DATA11 = ALT3,
    MUX_PAD_UART3_RTS_B__ENET1_1588_EVENT1_OUT = ALT4,
    MUX_PAD_UART3_RTS_B__GPIO1_IO27 = ALT5,
    MUX_PAD_UART3_RTS_B__WDOG1_WDOG_B = ALT8
};

enum MUX_PAD_UART3_RX_DATA {
    MUX_PAD_UART3_RX_DATA__UART3_RX = ALT0,
    MUX_PAD_UART3_RX_DATA__ENET2_RDATA03 = ALT1,
    MUX_PAD_UART3_RX_DATA__RESERVED_ALT2 = ALT2,
    MUX_PAD_UART3_RX_DATA__CSI_DATA00 = ALT3,
    MUX_PAD_UART3_RX_DATA__UART2_RTS_B = ALT4,
    MUX_PAD_UART3_RX_DATA__GPIO1_IO25 = ALT5,
    MUX_PAD_UART3_RX_DATA__EPIT1_OUT = ALT8
};

enum MUX_PAD_UART3_TX_DATA {
    MUX_PAD_UART3_TX_DATA__UART3_TX = ALT0,
    MUX_PAD_UART3_TX_DATA__ENET2_RDATA02 = ALT1,
    MUX_PAD_UART3_TX_DATA__RESERVED_ALT2 = ALT2,
    MUX_PAD_UART3_TX_DATA__CSI_DATA01 = ALT3,
    MUX_PAD_UART3_TX_DATA__UART2_CTS_B = ALT4,
    MUX_PAD_UART3_TX_DATA__GPIO1_IO24 = ALT5,
    MUX_PAD_UART3_TX_DATA__SJC_JTAG_ACT = ALT7,
    MUX_PAD_UART3_TX_DATA__ANATOP_OTG1_ID = ALT8
};

enum MUX_PAD_UART4_RX_DATA {
    MUX_PAD_UART4_RX_DATA__UART4_RX = ALT0,
    MUX_PAD_UART4_RX_DATA__ENET2_TDATA03 = ALT1,
    MUX_PAD_UART4_RX_DATA__I2C1_SDA = ALT2,
    MUX_PAD_UART4_RX_DATA__CSI_DATA13 = ALT3,
    MUX_PAD_UART4_RX_DATA__CSU_CSU_ALARM_AUT01 = ALT4,
    MUX_PAD_UART4_RX_DATA__GPIO1_IO29 = ALT5,
    MUX_PAD_UART4_RX_DATA__ECSPI2_SS0 = ALT8,
    MUX_PAD_UART4_RX_DATA__EPDC_PWRCTRL01 = ALT9
};

enum MUX_PAD_UART4_TX_DATA {
    MUX_PAD_UART4_TX_DATA__UART4_TX = ALT0,
    MUX_PAD_UART4_TX_DATA__ENET2_TDATA02 = ALT1,
    MUX_PAD_UART4_TX_DATA__I2C1_SCL = ALT2,
    MUX_PAD_UART4_TX_DATA__CSI_DATA12 = ALT3,
    MUX_PAD_UART4_TX_DATA__CSU_CSU_ALARM_AUT02 = ALT4,
    MUX_PAD_UART4_TX_DATA__GPIO1_IO28 = ALT5,
    MUX_PAD_UART4_TX_DATA__ECSPI2_SCLK = ALT8
};

enum MUX_PAD_UART5_RX_DATA {
    MUX_PAD_UART5_RX_DATA__UART5_RX = ALT0,
    MUX_PAD_UART5_RX_DATA__ENET2_COL = ALT1,
    MUX_PAD_UART5_RX_DATA__I2C2_SDA = ALT2,
    MUX_PAD_UART5_RX_DATA__CSI_DATA15 = ALT3,
    MUX_PAD_UART5_RX_DATA__CSU_CSU_INT_DEB = ALT4,
    MUX_PAD_UART5_RX_DATA__GPIO1_IO31 = ALT5,
    MUX_PAD_UART5_RX_DATA__ECSPI2_MISO = ALT8,
    MUX_PAD_UART5_RX_DATA__EPDC_PWRCTRL03 = ALT9
};

enum MUX_PAD_UART5_TX_DATA {
    MUX_PAD_UART5_TX_DATA__GPIO1_IO30 = ALT5,
    MUX_PAD_UART5_TX_DATA__ECSPI2_MOSI = ALT8,
    MUX_PAD_UART5_TX_DATA__EPDC_PWRCTRL02 = ALT9,
    MUX_PAD_UART5_TX_DATA__UART5_TX = ALT0,
    MUX_PAD_UART5_TX_DATA__ENET2_CRS = ALT1,
    MUX_PAD_UART5_TX_DATA__I2C2_SCL = ALT2,
    MUX_PAD_UART5_TX_DATA__CSI_DATA14 = ALT3,
    MUX_PAD_UART5_TX_DATA__CSU_CSU_ALARM_AUT00 = ALT4
};

#ifdef __cplusplus
}
#endif

#endif /* IOMUX_MUX_ENUMS_H */
/* clang-format on */
