#
# Driver for ADE9113
#
# Copyright 2026 Phoenix Systems
# Author: Jan Wiśniewski
#
# SPDX-License-Identifier: BSD-3-Clause

NAME := ade9113
LOCAL_SRCS := main.c dma.c ade9113.c msgapi.c sample.c
DEP_LIBS := libsdma libimx6ull-ecspi
DEPS := imx6ull-gpio

include $(binary.mk)
