#
# Makefile for Phoenix-RTOS imxrt117x-otp
#
# Copyright 2020 Phoenix Systems
#

$(PREFIX_PROG)imxrt117x-otp: $(PREFIX_O)otp/imxrt117x-otp/imxrt117x-otp.o
	$(LINK)

all: $(PREFIX_PROG_STRIPPED)imxrt117x-otp
