#
# Makefile for Phoenix-RTOS libspimctrl driver
#
# Copyright 2025 Phoenix Systems
#

NAME := libspimctrl
LOCAL_SRCS := flash.c flashdrv.c spimctrl.c
LOCAL_CFLAGS := -fvisibility=hidden

include $(static-lib.mk)
