#
# Makefile for Phoenix-RTOS 3 device drivers
#
# iMX RT drivers
#
# Copyright 2019 Phoenix Systems
#

CFLAGS += -DTARGET_IMXRT

include tty/libtty/Makefile
include multi/imxrt-multi/Makefile
include usb/imxrt-usbc/Makefile
include storage/imxrt-flash/Makefile
