#
# Phoenix-RTOS
#
# imx6ull-usb-loader - imx6ull usb module loader
#
# Copyright 2018 Phoenix Systems
# Author: Kamil Amanowicz
#

PROGS_SRCS := usb.c
PROGS := usb-imx

# include after all dependencies are set
include $(TOPDIR)/Makefile.rules
