#
# Makefile for ade7913
#
# Copyright 2021 Phoenix Systems
# Author: Marcin Baran
#
# %LICENSE%
#

NAME := ade7913-test
LOCAL_SRCS := ade7913.c ade7913-test.c
DEPS := imxrt-multi

include $(binary.mk)
