#
# Makefile for Phoenix-RTOS gr716-multi
#
# Copyright 2023 Phoenix Systems
#
# %LICENSE%
#

NAME := gr716-multi
LOCAL_SRCS := adc.c gpio.c spi.c uart.c gr716-multi.c
LOCAL_HEADERS := gr716-multi.h
DEP_LIBS := libtty libklog

include $(binary.mk)
