#
# Makefile for Phoenix-RTOS nrf91-multi
#
# Copyright 2024 Phoenix Systems
#

LOCAL_PATH := $(call my-dir)

NAME := nrf91-multi
SRCS := $(wildcard $(LOCAL_PATH)*.c)
DEP_LIBS := libtty libklog
LIBS := libdummyfs libklog

include $(binary.mk)
