#
# Makefile for Phoenix-RTOS spacewire
#
# Copyright 2025 Phoenix Systems
#
# SPDX-License-Identifier: BSD-3-Clause
#

NAME := grspwrtr
LOCAL_HEADERS := grspwrtr-srv.h
LOCAL_SRCS := grspwrtr-srv.c
LIBS := libgrspwrtr

include $(binary.mk)
