#
# Makefile for zynq7000-flash tests
#
# Copyright 2022 Phoenix Systems
#
# %LICENSE%
#

NAME := test_flashdrv
LOCAL_SRCS := flashdrv.c
DEP_LIBS := libflashdrv-zynq
LIBS := unity libstorage libcache

include $(binary.mk)
