/*
 * Phoenix-RTOS
 *
 * stm32l4-multi
 *
 * Peripheral register definitions for STM32N6 platform
 * Based on RM0486 STM32N647/657xx Reference manual by STMicroelectronics
 *
 * Copyright 2025 Phoenix Systems
 * Author: Jacek Maksymowicz
 *
 * This file is part of Phoenix-RTOS.
 *
 * %LICENSE%
 */

#ifndef _STM32N6_REGS_H_
#define _STM32N6_REGS_H_

enum rcc_regs {
	rcc_cr = 0x0,
	rcc_sr,
	rcc_stopcr,
	rcc_cfgr1 = 0x8,
	rcc_cfgr2,
	rcc_ckprotr,
	rcc_bdcr,
	rcc_hwrsr,
	rcc_rsr,
	rcc_lsecfgr = 0x10,
	rcc_msicfgr,
	rcc_hsicfgr,
	rcc_hsimcr,
	rcc_hsimsr,
	rcc_hsecfgr,
	rcc_pll1cfgr1 = 0x20,
	rcc_pll1cfgr2,
	rcc_pll1cfgr3,
	rcc_pll2cfgr1 = 0x24,
	rcc_pll2cfgr2,
	rcc_pll2cfgr3,
	rcc_pll3cfgr1 = 0x28,
	rcc_pll3cfgr2,
	rcc_pll3cfgr3,
	rcc_pll4cfgr1 = 0x2c,
	rcc_pll4cfgr2,
	rcc_pll4cfgr3,
	rcc_ic1cfgr = 0x31,
	rcc_ic2cfgr,
	rcc_ic3cfgr,
	rcc_ic4cfgr,
	rcc_ic5cfgr,
	rcc_ic6cfgr,
	rcc_ic7cfgr,
	rcc_ic8cfgr,
	rcc_ic9cfgr,
	rcc_ic10cfgr,
	rcc_ic11cfgr,
	rcc_ic12cfgr,
	rcc_ic13cfgr,
	rcc_ic14cfgr,
	rcc_ic15cfgr,
	rcc_ic16cfgr,
	rcc_ic17cfgr,
	rcc_ic18cfgr,
	rcc_ic19cfgr,
	rcc_ic20cfgr,
	rcc_cier = 0x49,
	rcc_cifr,
	rcc_cicr,
	rcc_ccipr1 = 0x51,
	rcc_ccipr2,
	rcc_ccipr3,
	rcc_ccipr4,
	rcc_ccipr5,
	rcc_ccipr6,
	rcc_ccipr7,
	rcc_ccipr8,
	rcc_ccipr9,
	rcc_ccipr12 = 0x5c,
	rcc_ccipr13,
	rcc_ccipr14,
	rcc_busrstr = 0x81,
	rcc_miscrstr,
	rcc_memrstr,
	rcc_ahb1rstr,
	rcc_ahb2rstr,
	rcc_ahb3rstr,
	rcc_ahb4rstr,
	rcc_ahb5rstr,
	rcc_apb1lrstr,
	rcc_apb1hrstr,
	rcc_apb2rstr,
	rcc_apb4lrstr = 0x8d,
	rcc_apb4hrstr,
	rcc_apb5rstr,
	rcc_divenr,
	rcc_busenr,
	rcc_miscenr,
	rcc_memenr,
	rcc_ahb1enr,
	rcc_ahb2enr,
	rcc_ahb3enr,
	rcc_ahb4enr,
	rcc_ahb5enr,
	rcc_apb1lenr,
	rcc_apb1henr,
	rcc_apb2enr,
	rcc_apb3enr,
	rcc_apb4lenr,
	rcc_apb4henr,
	rcc_apb5enr,
	rcc_divlpenr,
	rcc_buslpenr,
	rcc_misclpenr,
	rcc_memlpenr,
	rcc_ahb1lpenr,
	rcc_ahb2lpenr,
	rcc_ahb3lpenr,
	rcc_ahb4lpenr,
	rcc_ahb5lpenr,
	rcc_apb1llpenr,
	rcc_apb1hlpenr,
	rcc_apb2lpenr,
	rcc_apb3lpenr,
	rcc_apb4llpenr,
	rcc_apb4hlpenr,
	rcc_apb5lpenr,
	rcc_rdcr = 0x113,
	rcc_seccfgr0 = 0x1e0,
	rcc_privcfgr0,
	rcc_lockcfgr0,
	rcc_pubcfgr0,
	rcc_seccfgr1,
	rcc_privcfgr1,
	rcc_lockcfgr1,
	rcc_pubcfgr1,
	rcc_seccfgr2,
	rcc_privcfgr2,
	rcc_lockcfgr2,
	rcc_pubcfgr2,
	rcc_seccfgr3,
	rcc_privcfgr3,
	rcc_lockcfgr3,
	rcc_pubcfgr3,
	rcc_seccfgr4,
	rcc_privcfgr4,
	rcc_lockcfgr4,
	rcc_pubcfgr4,
	rcc_pubcfgr5,
	rcc_csr = 0x200,
	rcc_stopcsr = 0x202,
	rcc_busrstsr = 0x281,
	rcc_miscrstsr,
	rcc_memrstsr,
	rcc_ahb1rstsr,
	rcc_ahb2rstsr,
	rcc_ahb3rstsr,
	rcc_ahb4rstsr,
	rcc_ahb5rstsr,
	rcc_apb1lrstsr,
	rcc_apb1hrstsr,
	rcc_apb2rstsr,
	rcc_apb4lrstsr = 0x28d,
	rcc_apb4hrstsr,
	rcc_apb5rstsr,
	rcc_divensr,
	rcc_busensr,
	rcc_miscensr,
	rcc_memensr,
	rcc_ahb1ensr,
	rcc_ahb2ensr,
	rcc_ahb3ensr,
	rcc_ahb4ensr,
	rcc_ahb5ensr,
	rcc_apb1lensr,
	rcc_apb1hensr,
	rcc_apb2ensr,
	rcc_apb3ensr,
	rcc_apb4lensr,
	rcc_apb4hensr,
	rcc_apb5ensr,
	rcc_divlpensr,
	rcc_buslpensr,
	rcc_misclpensr,
	rcc_memlpensr,
	rcc_ahb1lpensr,
	rcc_ahb2lpensr,
	rcc_ahb3lpensr,
	rcc_ahb4lpensr,
	rcc_ahb5lpensr,
	rcc_apb1llpensr,
	rcc_apb1hlpensr,
	rcc_apb2lpensr,
	rcc_apb3lpensr,
	rcc_apb4llpensr,
	rcc_apb4hlpensr,
	rcc_apb5lpensr,
	rcc_privcfgsr0 = 0x3e1,
	rcc_pubcfgsr0 = 0x3e3,
	rcc_privcfgsr1 = 0x3e5,
	rcc_pubcfgsr1 = 0x3e7,
	rcc_privcfgsr2 = 0x3e9,
	rcc_pubcfgsr2 = 0x3eb,
	rcc_seccfgsr3,
	rcc_privcfgsr3,
	rcc_lockcfgsr3,
	rcc_pubcfgsr3,
	rcc_privcfgsr4 = 0x3f1,
	rcc_pubcfgsr4 = 0x3f3,
	rcc_pubcfgsr5,
	rcc_ccr = 0x400,
	rcc_stopccr = 0x402,
	rcc_busrstcr = 0x481,
	rcc_miscrstcr,
	rcc_memrstcr,
	rcc_ahb1rstcr,
	rcc_ahb2rstcr,
	rcc_ahb3rstcr,
	rcc_ahb4rstcr,
	rcc_ahb5rstcr,
	rcc_apb1lrstcr,
	rcc_apb1hrstcr,
	rcc_apb2rstcr,
	rcc_apb4lrstcr = 0x48d,
	rcc_apb4hrstcr,
	rcc_apb5rstcr,
	rcc_divencr,
	rcc_busencr,
	rcc_miscencr,
	rcc_memencr,
	rcc_ahb1encr,
	rcc_ahb2encr,
	rcc_ahb3encr,
	rcc_ahb4encr,
	rcc_ahb5encr,
	rcc_apb1lencr,
	rcc_apb1hencr,
	rcc_apb2encr,
	rcc_apb3encr,
	rcc_apb4lencr,
	rcc_apb4hencr,
	rcc_apb5encr,
	rcc_divlpencr,
	rcc_buslpencr,
	rcc_misclpencr,
	rcc_memlpencr,
	rcc_ahb1lpencr,
	rcc_ahb2lpencr,
	rcc_ahb3lpencr,
	rcc_ahb4lpencr,
	rcc_ahb5lpencr,
	rcc_apb1llpencr,
	rcc_apb1hlpencr,
	rcc_apb2lpencr,
	rcc_apb3lpencr,
	rcc_apb4llpencr,
	rcc_apb4hlpencr,
	rcc_apb5lpencr,
	rcc_privcfgcr0 = 0x5e1,
	rcc_pubcfgcr0 = 0x5e3,
	rcc_privcfgcr1 = 0x5e5,
	rcc_pubcfgcr1 = 0x5e7,
	rcc_privcfgcr2 = 0x5e9,
	rcc_pubcfgcr2 = 0x5eb,
	rcc_privcfgcr3 = 0x5ed,
	rcc_pubcfgcr3 = 0x5ef,
	rcc_privcfgcr4 = 0x5f1,
	rcc_pubcfgcr4 = 0x5f3,
	rcc_pubcfgcr5,
};


enum pwr_regs {
	pwr_cr1 = 0x0,
	pwr_cr2,
	pwr_cr3,
	pwr_cr4,
	pwr_voscr = 0x8,
	pwr_bdcr1,
	pwr_bdcr2,
	pwr_dbpcr,
	pwr_cpucr,
	pwr_svmcr1,
	pwr_svmcr2,
	pwr_svmcr3,
	pwr_wkupcr = 0x14,
	pwr_wkupsr,
	pwr_wkupepr,
	pwr_seccfgr = 0x1c,
	pwr_privcfgr,
};


enum spi_regs {
	spi_cr1 = 0x0,
	spi_cr2,
	spi_cfg1,
	spi_cfg2,
	spi_ier,
	spi_sr,
	spi_ifcr,
	spi_txdr = 0x8,
	spi_rxdr = 0xc,
	spi_crcpoly = 0x10,
	spi_txcrc,
	spi_rxcrc,
	spi_udrdr,
	spi_i2scfgr,
};


enum adc_regs {
	adc_isr = 0x0,
	adc_ier,
	adc_cr,
	adc_cfgr1,
	adc_cfgr2,
	adc_smpr1,
	adc_smpr2,
	adc_pcsel,
	adc_sqr1 = 0xc,
	adc_sqr2,
	adc_sqr3,
	adc_sqr4,
	adc_dr,
	adc_jsqr = 0x13,
	adc_ofcfgr1,
	adc_ofcfgr2,
	adc_ofcfgr3,
	adc_ofcfgr4,
	adc_ofr1,
	adc_ofr2,
	adc_ofr3,
	adc_ofr4,
	adc_gcomp,
	adc_jdr1 = 0x20,
	adc_jdr2,
	adc_jdr3,
	adc_jdr4,
	adc_awd2cr = 0x28,
	adc_awd3cr,
	adc_awd1ltr,
	adc_awd1htr,
	adc_awd2ltr,
	adc_awd2htr,
	adc_awd3ltr,
	adc_awd3htr,
	adc_difsel,
	adc_calfact,
	adc_or = 0x34,
};


enum tim_regs {
	tim_cr1,
	tim_cr2,
	tim_smcr,
	tim_dier,
	tim_sr,
	tim_egr,
	tim_ccmr1,
	tim_ccmr2,
	tim_ccer,
	tim_cnt,
	tim_psc,
	tim_arr,
	tim_rcr,
	tim_ccr1,
	tim_ccr2,
	tim_ccr3,
	tim_ccr4,
	tim_bdtr,
	tim_ccr5,
	tim_ccr6,
	tim_ccmr3,
	tim_dtr2,
	tim_ecr,
	tim_tisel,
	tim_af1,
	tim_af2,
	tim_dcr = 0xf7,
	tim_dmar,
};


#endif /* _STM32N6_REGS_H_ */
