#
# Makefile for Phoenix-RTOS GRLIB SpW Router
#
# Copyright 2026 Phoenix Systems
#
# SPDX-License-Identifier: BSD-3-Clause
#

NAME := libgrspwrtr
LOCAL_HEADERS := libgrspwrtr.h
LOCAL_SRCS := libgrspwrtr.c

include $(static-lib.mk)
