#
# Makefile for Phoenix-RTOS imx6ull-uart driver
#
# Copyright 2018 Phoenix Systems
#

LIB := libsdma.a
LIB_SRCS := sdma-lib.c
INSTALL_HDRS := sdma-api.h sdma-lib.h

PROGS := sdma-driver

# include after all dependencies are set
include $(TOPDIR)/Makefile.rules
