#
# Makefile for Phoenix-RTOS librmap
#
# Copyright 2026 Phoenix Systems
#
# SPDX-License-Identifier: BSD-3-Clause
#

NAME := librmap
LOCAL_SRCS := rmap.c
LOCAL_HEADERS := rmap.h

include $(static-lib.mk)
