#
# Makefile for Phoenix-RTOS spacewire
#
# Copyright 2025 Phoenix Systems
#
# %LICENSE%
#

NAME := spacewire
LOCAL_HEADERS := spacewire.h
LOCAL_SRCS := spacewire.c

# FIXME: adapt code to array-bounds checker 
LOCAL_CFLAGS := -Wno-array-bounds

include $(static-lib.mk)
