#
# Makefile for Phoenix-RTOS
#
# Copyright 2025 Phoenix Systems
#

ifeq ($(PCI_EXPRESS_XILINX_AXI),y)
  NAME := pcie-xilinx-axi
  LOCAL_SRCS := pcie-xilinx-axi.c
  LOCAL_HEADERS := pcie-xilinx-axi.h
  include $(static-lib.mk)
endif
