#
# Makefile for Phoenix-RTOS grlib-multi
#
# Copyright 2023 Phoenix Systems
#
# SPDX-License-Identifier: BSD-3-Clause
#

NAME := grlib-multi
LOCAL_SRCS := adc.c gpio.c spi.c uart.c grlib-multi.c
LOCAL_HEADERS := grlib-multi.h
DEP_LIBS := libtty libklog libpseudodev libgrdmac2 libgrspw-srv libgrspw libgrgpio libgrgpio-msg

include $(binary.mk)
