#
# Makefile for flash emulator
#
# Copyright 2021 Phoenix Systems
#
# %LICENSE%
#

NAME := host-flash
LOCAL_SRCS := host-flash.c host-flashsrv.c
LOCAL_HEADERS := host-flashsrv.h

include $(static-lib.mk)
