#
# Makefile for Phoenix-RTOS TTY abstraction layer
#
# Copyright 2018 Phoenix Systems
#

LIB := libtty.a
LIB_SRCS := libtty.c libtty_disc.c
LIB_HDRS := libtty.h

# include after all dependencies are set
include $(TOPDIR)/Makefile.rules
