#
# Phoenix-RTOS
#
# GR765 storage tests
#
# Copyright 2026 Phoenix Systems
# Author: Amelia Waszkowska
#

NAME := gr765-flash-tests
LOCAL_SRCS := tests.c flashsrv_tests.c
DEPS := flashdrv
LIBS := libstorage libptable

include $(binary.mk)

