#
# Makefile for Phoenix-RTOS libstm32_extflash driver
#
# Copyright 2026 Phoenix Systems
#

NAME := libstm32_extflash
LOCAL_SRCS := flashdrv.c
LOCAL_CFLAGS := -fvisibility=hidden

include $(static-lib.mk)
