#
# Makefile for Phoenix-RTOS 3 device drivers
#
# ZynqMP drivers
#
# Copyright 2024 Phoenix Systems
#

DEFAULT_COMPONENTS := zynq-uart zynq-flash zynqmp-can zynq-pwm uart16550

DEFAULT_COMPONENTS += libzynqpwm
