#
# Makefile for Phoenix-RTOS 3 device drivers
#
# zynq7000 drivers
#
# Copyright 2021 Phoenix Systems
#

DEFAULT_COMPONENTS := zynq7000-uart
DEFAULT_COMPONENTS += libflashdrv-zynq zynq7000-flash test_flashdrv
