#
# Makefile for Phoenix-RTOS 3 device drivers
#
# zynq7000 drivers
#
# Copyright 2021 Phoenix Systems
#

DEFAULT_COMPONENTS := zynq7000-uart uart16550 zynq7000-pwm zynq7000-xgpio zynq7000-spi zynq7000-xspi zynq7000-gpio
DEFAULT_COMPONENTS += libflashdrv-zynq zynq7000-flash test_flashdrv libspi-msg libzynq7000-gpio-msg libzynq7000pwm
DEFAULT_COMPONENTS += libsensors sensors
DEFAULT_COMPONENTS += zynq7000-i2c zynq7000-sdcard
