#
# Makefile for Phoenix-RTOS 3 device drivers
#
# iMX6ULL drivers
#
# Copyright 2019 Phoenix Systems
#

DEFAULT_COMPONENTS := imx6ull-sdma imx6ull-gpio libimx6ull-ecspi libimx6ull-qspi
DEFAULT_COMPONENTS += imx6ull-flash
DEFAULT_COMPONENTS += imx6ull-flashnor
DEFAULT_COMPONENTS += libusbclient cdc-demo
DEFAULT_COMPONENTS += imx6ull-uart imx6ull-otp
DEFAULT_COMPONENTS += imx6ull-wdg imx6ull-i2c imx6ull-sdio

DEFAULT_COMPONENTS += libusbehci umass usbacm
DEFAULT_COMPONENTS += libsensors sensors
