#
# Makefile for Phoenix-RTOS 3 device drivers
#
# TDA4VM drivers
#
# Copyright 2025 Phoenix Systems
#

DEFAULT_COMPONENTS := uart16550
DEFAULT_COMPONENTS += libspi-tda4vm mcspidemo
DEFAULT_COMPONENTS += libcan-tda4vm mcandemo
DEFAULT_COMPONENTS += libgpio-tda4vm
