#
# Makefile for Phoenix-RTOS 3 device drivers
#
# riscv64-gr765 drivers
#
# Copyright 2025 Phoenix Systems
#

DEFAULT_COMPONENTS := grlib-uart grlib-can-core grlib-can-driver can-sender-stress can-receiver-stress can-test-app
