#
# Makefile for Phoenix-RTOS 3 device drivers
#
# riscv64-gr765 drivers
#
# Copyright 2025 Phoenix Systems
#

DEFAULT_COMPONENTS := grlib-uart grspw2 grspwrtr
DEFAULT_COMPONENTS += gri2cmst i2c-scan
DEFAULT_COMPONENTS += grspictrl
