#
# Makefile for Phoenix-RTOS 3 device drivers
#
# STM32 drivers
#
# Copyright 2019, 2020 Phoenix Systems
#

CFLAGS += -DTARGET_STM32 -DTARGET_STM32L4

include tty/libtty/Makefile
include multi/stm32l4-multi/Makefile
