#
# Makefile for Phoenix-RTOS 3 device drivers
#
# iMX6ULL drivers
#
# Copyright 2019 Phoenix Systems
#

DEFAULT_COMPONENTS := imx6ull-sdma imx6ull-gpio libimx6ull-ecspi
DEFAULT_COMPONENTS += imx6ull-flash imx6ull-nandtool
DEFAULT_COMPONENTS += libusbclient
DEFAULT_COMPONENTS += imx6ull-uart imx6ull-otp

# FIXME: rename usb host component
DEFAULT_COMPONENTS += libusbehci
