#
# Phoenix-RTOS
#
# GR716 storage tests
#
# Copyright 2023 Phoenix Systems
# Author: Lukasz Leczkowski
#

NAME := gr716-flash-tests
LOCAL_SRCS := tests.c flashsrv_mfs_tests.c flashsrv_raw_tests.c
DEPS := gr716-flash
DEP_LIBS := libflashdrv-gr716
LIBS := libptable libmeterfs

include $(binary.mk)

