#
# Makefile for Phoenix-RTOS imxrt117x-cm4 driver
#
# Copyright 2018, 2019 Phoenix Systems
#

NAME := imxrt117x-cm4
LOCAL_SRCS := imxrt117x-cm4.c
LOCAL_HEADERS := imxrt117x-cm4.h
include $(binary.mk)
