#
# Makefile for Phoenix-RTOS spacewire
#
# Copyright 2025 Phoenix Systems
#
# %LICENSE%
#

NAME := grspw2
LOCAL_SRCS := grspw2.c
DEP_LIBS := spacewire

# FIXME: adapt code to array-bounds checker 
LOCAL_CFLAGS := -Wno-array-bounds

include $(binary.mk)
