#
# Makefile for Phoenix-RTOS spacewire
#
# Copyright 2025 Phoenix Systems
#
# SPDX-License-Identifier: BSD-3-Clause
#

NAME := grspw2
LOCAL_SRCS := grspw2.c
DEP_LIBS := libgrspw-srv libgrspw

include $(binary.mk)
