#
# Makefile for Phoenix-RTOS imx6ull ehci
#
# Copyright 2018 Phoenix Systems
#

PROGS_SRCS = telit-le910.c
PROGS = telit-le910
PROGS_LIBS := libusb.a

# include after all dependencies are set
include $(TOPDIR)/Makefile.rules
