#
# Makefile for Phoenix-RTOS stm32-multi
#
# Copyright 2018 Phoenix Systems
#

PROGS_SRCS = adc.c gpio.c i2c.c lcd.c rcc.c rtc.c stm32-multi.c flash.c uart.c spi.c
PROGS := stm32-multi

# include after all dependencies are set
include $(TOPDIR)/Makefile.rules
