#
# Makefile for Phoenix-RTOS Zynq PCI Express driver
#
# Copyright 2025 Phoenix Systems
#

NAME := pcie
LOCAL_SRCS := pcie.c
LOCAL_LDFLAGS := -Ttext=100000
LOCAL_CFLAGS := -Wno-error -O0
include $(binary.mk)
