#
#Makefile for Phoenix - RTOS tda4vm - gpio
#
#Copyright 2026 Phoenix Systems
#

# TDA4VM MCU SPI library
NAME := libgpio-tda4vm
LOCAL_SRCS := gpio-tda4vm.c
LOCAL_HEADERS := gpio-tda4vm.h
include $(static-lib.mk)
