#
# Makefile for Phoenix-RTOS TTY abstraction layer
#
# Copyright 2018 Phoenix Systems
#

LIB := libehci-imx6ull.a
LIB_SRCS := dma.c ehci.c phy.c
INSTALL_HDRS := ehci.h dma.h

# include after all dependencies are set
include $(TOPDIR)/Makefile.rules
