#
# Makefile for Phoenix-RTOS imx6ull-ehci
#
# Copyright 2018, 2019 Phoenix Systems
#

# FIXME: rename usb host component
NAME := libusbehci
LOCAL_SRCS := ehci.c dma.c phy.c
LOCAL_HEADERS := dma.h ehci.h
DEPS := usb
include $(static-lib.mk)
