#
# Makefile for Phoenix-RTOS imx6ull-ecspi driver
#
# Copyright 2018 Phoenix Systems
#

LIB := libecspi.a
LIB_SRCS := ecspi-lib.c
INSTALL_HDRS := ecspi-api.h

PROGS := imx6ull-ecspi
PROGS_SRCS := imx6ull-ecspi.c

# include after all dependencies are set
include $(TOPDIR)/Makefile.rules