#
# Makefile for sdio library
#
# Copyright 2022 Phoenix Systems
# Author: Artur Miller
#
# This file is part of Phoenix-RTOS.
#
# %LICENSE%
#

NAME := sdio-common
LOCAL_HEADERS := sdio.h
include $(static-lib.mk)
