#
# Makefile for Phoenix-RTOS imx6ull-ehci
#
# Copyright 2018, 2019 Phoenix Systems
#

# FIXME: rename usb host component
NAME := libusbehci
LOCAL_SRCS := ehci.c ehci-hub.c phy-$(TARGET_SUBFAMILY).c

include $(static-lib.mk)
