#
# Makefile for Phoenix-RTOS grlib-multi
#
# Copyright 2023 Phoenix Systems
#
# %LICENSE%
#

NAME := grlib-can
LOCAL_SRCS := grlib-can.c
LOCAL_HEADERS := grlib-can.h

LOCAL_CFLAGS = -Wno-error -fno-omit-frame-pointer

include $(binary.mk)
