#
# Makefile for Phoenix-RTOS pc-tty drivers
#
# Copyright 2017, 2018 Phoenix Systems
# Copyright 2001, 2005-2006 Pawel Pisarczyk
#

PROGS_SRCS := ttypc.c ttypc_virt.c ttypc_vtf.c ttypc_vga.c ttypc_kbd.c
PROGS := pc-tty

# include after all dependencies are set
include $(TOPDIR)/Makefile.rules
