#
# Makefile for Phoenix-RTOS imu server
#
# Copyright 2021 Phoenix Systems
#
#

NAME := imx6ull-sensi2c
LOCAL_SRCS := imx6ull-sensi2c.c
LOCAL_HEADERS := imx6ull-sensi2c.h
include $(static-lib.mk)


# TODO: make an API header installed so the message structure is not unknown
