# vim:sw=2:ts=2
name: lint

# on events
on:
  push:
    branches:
      - master
      - 'feature/*'
  pull_request:
    branches:
      - master
      - 'feature/*'

jobs:
  call-lint:
    uses: phoenix-rtos/phoenix-rtos-project/.github/workflows/lint.yml@master
