#
# Makefile for Phoenix-RTOS imx6ull-uart driver
#
# Copyright 2018 Phoenix Systems
#

PROGS := imx6ull-gpio
INSTALL_HDRS := imx6ull-gpio.h

# include after all dependencies are set
include $(TOPDIR)/Makefile.rules
